import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, onValue, runTransaction } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js?v=8.0.0";
import { makeRoomController } from "./room-helper.js?v=8.0.0";
import { createSocial } from "./social.js?v=8.0.0";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=id=>document.getElementById(id);
const els={homeView:$('homeView'),lobbyView:$('lobbyView'),gameView:$('gameView'),playerName:$('playerName'),avatarPicker:$('avatarPicker'),create:$('createRoomBtn'),showJoin:$('showJoinBtn'),joinBox:$('joinBox'),roomCodeInput:$('roomCodeInput'),join:$('joinRoomBtn'),copy:$('copyCodeBtn'),share:$('shareRoomBtn'),leaveLobby:$('leaveLobbyBtn'),roomCodeLabel:$('roomCodeLabel'),status:$('statusBanner'),top:$('topPoints'),bottom:$('bottomPoints'),barW:$('barWhite'),barB:$('barBlack'),offW:$('offWhite'),offB:$('offBlack'),roll:$('rollBtn'),diceRack:$('diceRack'),diceHint:$('diceHint'),myInfo:$('myInfo'),oppInfo:$('opponentInfo'),shareGame:$('shareInGameBtn'),rematch:$('rematchBtn'),leaveGame:$('leaveGameBtn'),connection:$('connectionBadge'),reconnect:$('reconnectBanner'),toast:$('toast')};
const state={uid:null,roomCode:null,room:null,roomUnsub:null,avatar:'😎',selected:null};
const DICE=['⚀','⚁','⚂','⚃','⚄','⚅'];
function setView(n){['home','lobby','game'].forEach(x=>els[x+'View'].classList.toggle('active',x===n))}
function toast(t){els.toast.textContent=t;els.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add('hidden'),1900)}
function profile(){return{name:(els.playerName.value||'').trim().slice(0,18),avatar:state.avatar}}
function otherUid(r=state.room){return r?(r.hostUid===state.uid?r.guestUid:r.hostUid):null}
function colorOf(r=state.room,uid=state.uid){return r?.game?.colors?.w===uid?'w':r?.game?.colors?.b===uid?'b':null}
function opp(c){return c==='w'?'b':'w'}
function sign(c){return c==='w'?1:-1}
function own(v,c){return c==='w'?v>0:v<0}
function countOwn(v,c){return own(v,c)?Math.abs(v):0}
function cloneGame(g){return{...g,board:[...g.board],bar:{...g.bar},off:{...g.off},dice:[...(g.dice||[])],remaining:[...(g.remaining||[])]}}
function initialBoard(){const b=Array(24).fill(0);b[23]=2;b[12]=5;b[7]=3;b[5]=5;b[0]=-2;b[11]=-5;b[16]=-3;b[18]=-5;return b}
function allHome(g,c){if(g.bar[c]>0)return false;for(let i=0;i<24;i++)if(own(g.board[i],c)){if(c==='w'&&i>5)return false;if(c==='b'&&i<18)return false}return true}
function canLand(g,to,c){const v=g.board[to];return !own(v,opp(c))||Math.abs(v)<=1}
function movesForDie(g,c,die){const out=[];if(g.bar[c]>0){const to=c==='w'?24-die:die-1;if(canLand(g,to,c))out.push({from:'bar',to,die});return out}for(let from=0;from<24;from++){if(!own(g.board[from],c))continue;const to=from+(c==='w'?-die:die);if(to>=0&&to<24){if(canLand(g,to,c))out.push({from,to,die});continue}if(!allHome(g,c))continue;if(c==='w'&&to<0){const exact=die===from+1,over=die>from+1&&!g.board.slice(from+1,6).some(v=>own(v,c));if(exact||over)out.push({from,to:'off',die})}if(c==='b'&&to>23){const exact=die===24-from,over=die>24-from&&!g.board.slice(18,from).some(v=>own(v,c));if(exact||over)out.push({from,to:'off',die})}}return out}
function applyMove(g,c,m){const n=cloneGame(g),sgn=sign(c);if(m.from==='bar')n.bar[c]--;else n.board[m.from]-=sgn;if(m.to==='off')n.off[c]++;else{const ov=n.board[m.to];if(own(ov,opp(c))&&Math.abs(ov)===1){n.board[m.to]=0;n.bar[opp(c)]++}n.board[m.to]+=sgn}const idx=n.remaining.indexOf(m.die);if(idx>=0)n.remaining.splice(idx,1);return n}
function sequences(g,c,dice=g.remaining||[]){if(!dice.length)return[[]];let out=[];const tried=new Set();for(let i=0;i<dice.length;i++){const d=dice[i];if(tried.has(d))continue;tried.add(d);const ms=movesForDie(g,c,d);for(const m of ms){const n=applyMove({...g,remaining:[...dice]},c,m),rest=[...dice];rest.splice(rest.indexOf(d),1);n.remaining=rest;for(const tail of sequences(n,c,rest))out.push([m,...tail])}}return out.length?out:[[]]}
function bestSequences(g,c){let seqs=sequences(g,c,g.remaining||[]),max=Math.max(...seqs.map(x=>x.length));seqs=seqs.filter(x=>x.length===max);if(max===1&&new Set(g.remaining||[]).size>1){const high=Math.max(...seqs.map(x=>x[0]?.die||0));seqs=seqs.filter(x=>(x[0]?.die||0)===high)}return seqs}
function firstMoves(g,c){const seqs=bestSequences(g,c),map=new Map();for(const s of seqs){if(!s[0])continue;const m=s[0],k=`${m.from}-${m.to}-${m.die}`;map.set(k,m)}return[...map.values()]}
function randomDie(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%6+1}
function playerCard(p,c,turn){return`<span class="ava">${p?.avatar||'😎'}</span><div><b>${p?.name||'لاعب'}</b><small>${c==='w'?'الفاتح':'الداكن'}${turn?' • دوره الآن':''}</small></div>`}
async function startGame(r){if(!r||r.hostUid!==state.uid||!r.guestUid)return;const w=Math.random()<.5?r.hostUid:r.guestUid,b=w===r.hostUid?r.guestUid:r.hostUid,turn=Math.random()<.5?'w':'b';await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='waiting'||room.game)return;room.status='playing';room.game={colors:{w,b},board:initialBoard(),bar:{w:0,b:0},off:{w:0,b:0},turn,dice:[],remaining:[],winner:null,moveNo:0,lastMove:null,matchNo:1,startedAt:Date.now()};return room})}
async function roll(){state.selected=null;await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const g=room.game,c=colorOf(room,state.uid);if(g.turn!==c||(g.remaining||[]).length)return;const d1=randomDie(),d2=randomDie(),remaining=d1===d2?[d1,d1,d1,d1]:[d1,d2];g.dice=[d1,d2];g.remaining=remaining;g.lastRoll={c,d1,d2,at:Date.now()};if(!firstMoves(g,c).length){g.turn=opp(c);g.dice=[];g.remaining=[]}return room})}
async function doMove(from,to,die){state.selected=null;await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const c=colorOf(room,state.uid),g=room.game;if(g.turn!==c)return;const legal=firstMoves(g,c).find(m=>String(m.from)===String(from)&&String(m.to)===String(to)&&m.die===die);if(!legal)return;const n=applyMove(g,c,legal);n.moveNo=(g.moveNo||0)+1;n.lastMove={c,...legal,at:Date.now()};if(n.off[c]>=15){n.winner=c;room.status='finished';n.remaining=[];n.dice=[];room.game=n;return room}if(!n.remaining.length||!firstMoves(n,c).length){n.turn=opp(c);n.remaining=[];n.dice=[]}room.game=n;return room})}
async function rematch(){state.selected=null;await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='finished'||!room.game)return;const old=room.game.colors;room.status='playing';room.game={colors:{w:old.b,b:old.w},board:initialBoard(),bar:{w:0,b:0},off:{w:0,b:0},turn:Math.random()<.5?'w':'b',dice:[],remaining:[],winner:null,moveNo:0,lastMove:null,matchNo:(room.game.matchNo||1)+1,startedAt:Date.now()};return room})}
function orientation(c){return c==='w'?{top:[12,13,14,15,16,17,18,19,20,21,22,23],bottom:[11,10,9,8,7,6,5,4,3,2,1,0]}:{top:[11,10,9,8,7,6,5,4,3,2,1,0],bottom:[12,13,14,15,16,17,18,19,20,21,22,23]}}
function checkerHtml(c,n){const cls=c==='w'?'white':'black';return Array.from({length:Math.min(n,5)},()=>`<i class="checker ${cls}"></i>`).join(')+(n>5?`<b class="count-badge">${n}</b>`:'')}
function renderPoint(idx,pos,g,c,legal){const v=g.board[idx],n=Math.abs(v),pc=v>0?'w':v<0?'b':null,b=document.createElement('button');b.className=`bg-point ${pos} ${idx%2?'alt':''}`;b.dataset.point=idx;const stack=document.createElement('span');stack.className='checker-stack';if(pc)stack.innerHTML=checkerHtml(pc,n);b.appendChild(stack);const canSelect=pc===c&&g.bar[c]===0&&legal.some(m=>m.from===idx);if(canSelect)b.classList.add('selectable');if(String(state.selected)===String(idx))b.classList.add('selected');const dests=state.selected!=null?legal.filter(m=>String(m.from)===String(state.selected)):[];if(dests.some(m=>m.to===idx))b.classList.add('destination');b.addEventListener('click',()=>{if(dests.some(m=>m.to===idx)){const opts=dests.filter(m=>m.to===idx);doMove(state.selected,idx,opts[0].die)}else if(canSelect){state.selected=idx;render(state.room)}});return b}
function render(room){state.room=room;const g=room.game;if(!g)return;const me=colorOf(room),oc=opp(me),ouid=otherUid(room),legal=room.status==='playing'&&g.turn===me?firstMoves(g,me):[];els.roomCodeLabel.textContent=state.roomCode;els.myInfo.innerHTML=playerCard(room.players?.[state.uid],me,room.status==='playing'&&g.turn===me);els.oppInfo.innerHTML=playerCard(room.players?.[ouid],oc,room.status==='playing'&&g.turn===oc);els.myInfo.classList.toggle('turn',room.status==='playing'&&g.turn===me);els.oppInfo.classList.toggle('turn',room.status==='playing'&&g.turn===oc);const o=orientation(me);els.top.innerHTML='';els.bottom.innerHTML='';o.top.forEach(i=>els.top.appendChild(renderPoint(i,'top',g,me,legal)));o.bottom.forEach(i=>els.bottom.appendChild(renderPoint(i,'bottom',g,me,legal)));
 for(const [el,c] of [[els.barW,'w'],[els.barB,'b']]){el.innerHTML=checkerHtml(c,g.bar[c]||0);el.classList.toggle('selectable',c===me&&g.bar[c]>0&&legal.some(m=>m.from==='bar'));if(c===me&&g.bar[c]>0)el.onclick=()=>{state.selected='bar';render(state.room)};else el.onclick=null}
 els.offW.querySelector('b').textContent=g.off.w;els.offB.querySelector('b').textContent=g.off.b;const offMoves=state.selected!=null?legal.filter(m=>String(m.from)===String(state.selected)&&m.to==='off'):[];els.offW.classList.toggle('destination',me==='w'&&offMoves.length>0);els.offB.classList.toggle('destination',me==='b'&&offMoves.length>0);const offEl=me==='w'?els.offW:els.offB;offEl.onclick=offMoves.length?()=>doMove(state.selected,'off',offMoves[0].die):null;
 const remaining=[...(g.remaining||[])];els.diceRack.innerHTML=(g.dice?.length?g.dice:[null,null]).map((d,i)=>`<span class="${d&&!remaining.includes(d)?'used':''}">${d?DICE[d-1]:'🎲'}</span>`).join('');els.roll.disabled=room.status!=='playing'||g.turn!==me||remaining.length>0;els.rematch.disabled=room.status!=='finished';if(room.status==='finished'){els.status.textContent=g.winner===me?'🏆 كسبت الطاولة!':'صاحبك كسب الطاولة';els.diceHint.textContent='انتهت المباراة'}else if(g.turn!==me){els.status.textContent='دور صاحبك';els.diceHint.textContent='استنى صاحبك'}else if(remaining.length){els.status.textContent='اختار الحجر والنقلة';els.diceHint.textContent=`المتبقي: ${remaining.join(' ، ')}` }else{els.status.textContent='دورك — ارمِ الزهر';els.diceHint.textContent='اضغط ارمِ الزهر'}social.render(room)}
const ctrl=makeRoomController({db,auth,state,gameType:'backgammon',getProfile:profile,getSettings:()=>({}),setView,onRoom:render,onHostReady:startGame,toast});const social=createSocial({db,state,getProfile:profile,toast});
onValue(ref(db,'.info/connected'),s=>{const ok=s.val()===true;els.connection.textContent=ok?'متصل':'غير متصل';els.connection.classList.toggle('offline',!ok);els.reconnect.classList.toggle('hidden',ok)});
els.avatarPicker.addEventListener('click',e=>{const b=e.target.closest('button[data-avatar]');if(!b)return;state.avatar=b.dataset.avatar;els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));localStorage.setItem('coffee_avatar',state.avatar)});els.create.addEventListener('click',()=>{localStorage.setItem('coffee_name',profile().name);ctrl.createRoom()});els.showJoin.addEventListener('click',()=>els.joinBox.classList.toggle('hidden'));els.join.addEventListener('click',()=>ctrl.joinRoom(els.roomCodeInput.value));els.roomCodeInput.addEventListener('keydown',e=>e.key==='Enter'&&ctrl.joinRoom(els.roomCodeInput.value));els.roll.addEventListener('click',roll);els.rematch.addEventListener('click',rematch);els.leaveLobby.addEventListener('click',()=>{social.cleanup();ctrl.leaveLocal()});els.leaveGame.addEventListener('click',()=>{social.cleanup();ctrl.leaveLocal()});async function share(){const u=new URL('./backgammon.html',location.href);u.searchParams.set('room',state.roomCode);if(navigator.share){try{return await navigator.share({title:'القهوة — الطاولة',text:`تعالى نلعب طاولة — كود ${state.roomCode}`,url:u.href})}catch{}}await navigator.clipboard.writeText(u.href);toast('تم نسخ الرابط')}els.copy.addEventListener('click',()=>navigator.clipboard.writeText(state.roomCode).then(()=>toast('تم نسخ الكود')));els.share.addEventListener('click',share);els.shareGame.addEventListener('click',share);
(async()=>{els.playerName.value=localStorage.getItem('coffee_name')||'';state.avatar=localStorage.getItem('coffee_avatar')||'😎';els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===state.avatar));if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=8.0.0').catch(()=>{});await ctrl.resume()})().catch(console.error);
