import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, set, get, update, remove, onValue, runTransaction, onDisconnect } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js?v=7.3.0";
import { turnConfig } from "./turn-config.js?v=7.3.0";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=id=>document.getElementById(id);
const els={
 homeView:$('homeView'),lobbyView:$('lobbyView'),gameView:$('gameView'),playerName:$('playerName'),avatarPicker:$('avatarPicker'),timeControl:$('timeControl'),colorChoice:$('colorChoice'),boardThemeChoice:$('boardThemeChoice'),pieceThemeChoice:$('pieceThemeChoice'),gameBoardThemeChoice:$('gameBoardThemeChoice'),gamePieceThemeChoice:$('gamePieceThemeChoice'),createRoomBtn:$('createRoomBtn'),showJoinBtn:$('showJoinBtn'),joinBox:$('joinBox'),roomCodeInput:$('roomCodeInput'),joinRoomBtn:$('joinRoomBtn'),homeMessage:$('homeMessage'),connectionBadge:$('connectionBadge'),reconnectBanner:$('reconnectBanner'),soundBtn:$('soundBtn'),
 lobbyRoomCode:$('lobbyRoomCode'),copyCodeBtn:$('copyCodeBtn'),shareRoomBtn:$('shareRoomBtn'),lobbyPlayers:$('lobbyPlayers'),lobbyStatus:$('lobbyStatus'),leaveLobbyBtn:$('leaveLobbyBtn'),
 roomCodeLabel:$('roomCodeLabel'),opponentInfo:$('opponentInfo'),myInfo:$('myInfo'),opponentClock:$('opponentClock'),myClock:$('myClock'),capturedByMe:$('capturedByMe'),capturedByOpponent:$('capturedByOpponent'),offerDrawBtn:$('offerDrawBtn'),resignBtn:$('resignBtn'),shareInGameBtn:$('shareInGameBtn'),statusBanner:$('statusBanner'),chessBoard:$('chessBoard'),drawOfferBar:$('drawOfferBar'),acceptDrawBtn:$('acceptDrawBtn'),declineDrawBtn:$('declineDrawBtn'),
 reactions:$('reactions'),chatToggleBtn:$('chatToggleBtn'),chatUnread:$('chatUnread'),chatPanel:$('chatPanel'),chatCloseBtn:$('chatCloseBtn'),chatMessages:$('chatMessages'),chatForm:$('chatForm'),chatInput:$('chatInput'),voiceCallBtn:$('voiceCallBtn'),voiceCallLabel:$('voiceCallLabel'),voiceActiveBar:$('voiceActiveBar'),voiceStatusText:$('voiceStatusText'),voiceMuteBtn:$('voiceMuteBtn'),voiceHangupBtn:$('voiceHangupBtn'),remoteAudio:$('remoteAudio'),
 movesList:$('movesList'),moveCount:$('moveCount'),livePositionBtn:$('livePositionBtn'),downloadPgnBtn:$('downloadPgnBtn'),promotionModal:$('promotionModal'),promotionChoices:$('promotionChoices'),resultModal:$('resultModal'),resultEmoji:$('resultEmoji'),resultTitle:$('resultTitle'),resultText:$('resultText'),rematchBtn:$('rematchBtn'),resultHomeBtn:$('resultHomeBtn'),voiceIncomingModal:$('voiceIncomingModal'),voiceCallerName:$('voiceCallerName'),voiceAcceptBtn:$('voiceAcceptBtn'),voiceDeclineBtn:$('voiceDeclineBtn'),toast:$('toast')
};
const PIECE_GLYPH={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
const state={uid:null,roomCode:null,room:null,roomUnsub:null,selectedAvatar:'😎',selectedSquare:null,legalMoves:[],pendingPromotion:null,reviewFen:null,sound:true,lastChatCount:0,lastReactionAt:0,timerId:null,drag:null,peer:null,localStream:null,remoteStream:null,currentCallId:null,incomingCall:null,voiceSignalReady:false,pendingIce:[],seenIce:new Set(),remoteDescriptionSet:false,voiceMuted:false,processingVoice:false,installPrompt:null,serverOffset:0,claimingTimeout:false,audio:{}};

function setView(name){for(const v of ['home','lobby','game'])els[v+'View'].classList.toggle('active',v===name)}
function toast(msg){els.toast.textContent=msg;els.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add('hidden'),2200)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":'&#039;'}[m]))}
function roomRef(code=state.roomCode){return ref(db,`rooms/${code}`)}
async function ensureAuth(){if(!auth.currentUser)await signInAnonymously(auth);state.uid=auth.currentUser.uid}
function getProfile(){return{name:(els.playerName.value||'').trim().slice(0,18),avatar:state.selectedAvatar||'😎'}}
function saveProfile(){const p=getProfile();localStorage.setItem('coffee_name',p.name);localStorage.setItem('coffee_avatar',p.avatar);localStorage.setItem('chess_time',els.timeControl.value);localStorage.setItem('chess_color',els.colorChoice.value);localStorage.setItem('chess_board_theme',els.boardThemeChoice.value);localStorage.setItem('chess_piece_theme',els.pieceThemeChoice.value)}
function otherUid(room=state.room){if(!room)return null;return room.hostUid===state.uid?room.guestUid:room.hostUid}
function playerColor(room=state.room,uid=state.uid){if(!room?.game?.colors)return null;return room.game.colors.white===uid?'w':room.game.colors.black===uid?'b':null}
function playerIds(room){return [room.hostUid,room.guestUid].filter(Boolean)}

function normalizePieceTheme(v){const x=String(v||'classic');if(['classic','slate','wood','royal'].includes(x))return x;if(x==='gold')return'royal';if(x==='mono')return'slate';return'classic'}
function currentPieceTheme(){return normalizePieceTheme(els.gamePieceThemeChoice?.value||els.pieceThemeChoice?.value||localStorage.getItem('chess_piece_theme')||'classic')}
function pieceAsset(code,theme=currentPieceTheme()){
  const color=pieceColor(code)||'w',typ=pieceType(code)||'p';
  return `./assets/chess-pieces/${theme}/${color}${typ}.svg?v=7.3.0`;
}
function pieceImgHtml(code,extra=''){return `<img class="piece-svg ${extra}" src="${pieceAsset(code)}" alt="" draggable="false">`}
function applyVisualThemes(){
  const board=els.boardThemeChoice?.value||localStorage.getItem('chess_board_theme')||'classic';
  const pieces=normalizePieceTheme(els.pieceThemeChoice?.value||localStorage.getItem('chess_piece_theme')||'classic');
  document.documentElement.dataset.boardTheme=board;
  document.documentElement.dataset.pieceTheme=pieces;
}

function syncThemeControls(){const board=localStorage.getItem('chess_board_theme')||els.boardThemeChoice?.value||'classic',pieces=normalizePieceTheme(localStorage.getItem('chess_piece_theme')||els.pieceThemeChoice?.value||'classic');if(els.boardThemeChoice)els.boardThemeChoice.value=board;if(els.gameBoardThemeChoice)els.gameBoardThemeChoice.value=board;if(els.pieceThemeChoice)els.pieceThemeChoice.value=pieces;if(els.gamePieceThemeChoice)els.gamePieceThemeChoice.value=pieces;}
function renderPromotionChoices(color='w'){const palette=['q','r','b','n'];els.promotionChoices.innerHTML=palette.map(t=>`<button data-piece="${t}" aria-label="${t}">${pieceImgHtml(color==='w'?t.toUpperCase():t,'promo-svg')}</button>`).join('')}
function renderMiniBoard(){const mini=document.getElementById('miniBoard');if(!mini)return;const board=['r','n','b','q','k','b','n','r','p','p','p','p','p','p','p','p',...Array(32).fill(''), 'P','P','P','P','P','P','P','P','R','N','B','Q','K','B','N','R'];mini.innerHTML='';for(const code of board){if(code){const cell=document.createElement('span');cell.className='mini-piece';cell.innerHTML=pieceImgHtml(code);mini.appendChild(cell)}else mini.appendChild(document.createElement('i'));}}
function setVisualTheme(kind,value){if(kind==='board'){localStorage.setItem('chess_board_theme',value);if(els.boardThemeChoice)els.boardThemeChoice.value=value;if(els.gameBoardThemeChoice)els.gameBoardThemeChoice.value=value;}else{const normalized=normalizePieceTheme(value);localStorage.setItem('chess_piece_theme',normalized);if(els.pieceThemeChoice)els.pieceThemeChoice.value=normalized;if(els.gamePieceThemeChoice)els.gamePieceThemeChoice.value=normalized;}applyVisualThemes();renderPromotionChoices(playerColor(state.room)||'w');renderMiniBoard();if(state.room&&els.gameView.classList.contains('active'))renderGame(state.room);}
function nowMs(){return Date.now()+(Number(state.serverOffset)||0)}
function preloadSound(key,src){const a=new Audio(src);a.preload='auto';state.audio[key]=a;return a}

onAuthStateChanged(auth,u=>state.uid=u?.uid||null);
onValue(ref(db,'.info/connected'),snap=>{const ok=snap.val()===true;els.connectionBadge.textContent=ok?'متصل':'غير متصل';els.connectionBadge.classList.toggle('offline',!ok);els.reconnectBanner.classList.toggle('hidden',ok)});

// ---------------- Chess engine ----------------
function emptyPos(){return{board:Array(64).fill(null),turn:'w',castling:'KQkq',ep:-1,halfmove:0,fullmove:1}}
function startFen(){return'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'}
function squareName(i){return String.fromCharCode(97+(i%8))+(8-Math.floor(i/8))}
function squareIndex(s){if(!/^[a-h][1-8]$/.test(s||''))return-1;return (8-Number(s[1]))*8+(s.charCodeAt(0)-97)}
function pieceColor(p){return p?(p===p.toUpperCase()?'w':'b'):null}
function pieceType(p){return p?.toLowerCase()||''}
function opposite(c){return c==='w'?'b':'w'}
function onBoard(r,c){return r>=0&&r<8&&c>=0&&c<8}
function rc(i){return[Math.floor(i/8),i%8]}
function parseFen(fen){const [bp,turn='w',cast='-',ep='-',half='0',full='1']=String(fen||startFen()).split(' '),board=[];for(const row of bp.split('/')){for(const ch of row){if(/\d/.test(ch))for(let n=0;n<Number(ch);n++)board.push(null);else board.push(ch)}}while(board.length<64)board.push(null);return{board:board.slice(0,64),turn,castling:cast==='-'?'':cast,ep:ep==='-'?-1:squareIndex(ep),halfmove:Number(half)||0,fullmove:Number(full)||1}}
function boardFen(board){let out=[];for(let r=0;r<8;r++){let row='',empty=0;for(let c=0;c<8;c++){const p=board[r*8+c];if(!p)empty++;else{if(empty){row+=empty;empty=0}row+=p}}if(empty)row+=empty;out.push(row)}return out.join('/')}
function toFen(pos){return`${boardFen(pos.board)} ${pos.turn} ${pos.castling||'-'} ${pos.ep>=0?squareName(pos.ep):'-'} ${pos.halfmove} ${pos.fullmove}`}
function positionKey(pos){return`${boardFen(pos.board)} ${pos.turn} ${pos.castling||'-'} ${pos.ep>=0?squareName(pos.ep):'-'}`}
function clonePos(pos){return{board:[...pos.board],turn:pos.turn,castling:pos.castling,ep:pos.ep,halfmove:pos.halfmove,fullmove:pos.fullmove}}
function kingSquare(pos,color){const k=color==='w'?'K':'k';return pos.board.indexOf(k)}
function attacked(pos,sq,by){const [r,c]=rc(sq),b=pos.board;
  const pawn=by==='w'?'P':'p',pdr=by==='w'?1:-1;for(const dc of[-1,1]){const rr=r+pdr,cc=c+dc;if(onBoard(rr,cc)&&b[rr*8+cc]===pawn)return true}
  const knight=by==='w'?'N':'n';for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]){const rr=r+dr,cc=c+dc;if(onBoard(rr,cc)&&b[rr*8+cc]===knight)return true}
  const king=by==='w'?'K':'k';for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const rr=r+dr,cc=c+dc;if(onBoard(rr,cc)&&b[rr*8+cc]===king)return true}
  for(const[dr,dc]of[[-1,0],[1,0],[0,-1],[0,1]]){let rr=r+dr,cc=c+dc;while(onBoard(rr,cc)){const p=b[rr*8+cc];if(p){if(pieceColor(p)===by&&['r','q'].includes(pieceType(p)))return true;break}rr+=dr;cc+=dc}}
  for(const[dr,dc]of[[-1,-1],[-1,1],[1,-1],[1,1]]){let rr=r+dr,cc=c+dc;while(onBoard(rr,cc)){const p=b[rr*8+cc];if(p){if(pieceColor(p)===by&&['b','q'].includes(pieceType(p)))return true;break}rr+=dr;cc+=dc}}
  return false}
function inCheck(pos,color){const k=kingSquare(pos,color);return k>=0&&attacked(pos,k,opposite(color))}
function pushMove(moves,pos,from,to,extra={}){if(to<0||to>=64)return;const target=pos.board[to],color=pieceColor(pos.board[from]);if(target&&pieceColor(target)===color)return;if(target&&pieceType(target)==='k')return;moves.push({from,to,piece:pos.board[from],capture:target||null,...extra})}
function pseudoMoves(pos,color=pos.turn){const moves=[],b=pos.board;for(let from=0;from<64;from++){const p=b[from];if(!p||pieceColor(p)!==color)continue;const t=pieceType(p),[r,c]=rc(from);
  if(t==='p'){const dir=color==='w'?-1:1,start=color==='w'?6:1,promo=color==='w'?0:7,one=(r+dir)*8+c;if(onBoard(r+dir,c)&&!b[one]){if(r+dir===promo)for(const pr of['q','r','b','n'])pushMove(moves,pos,from,one,{promotion:pr});else pushMove(moves,pos,from,one);const two=(r+2*dir)*8+c;if(r===start&&!b[two])pushMove(moves,pos,from,two,{double:true})}for(const dc of[-1,1]){const rr=r+dir,cc=c+dc;if(!onBoard(rr,cc))continue;const to=rr*8+cc;if(b[to]&&pieceColor(b[to])!==color){if(rr===promo)for(const pr of['q','r','b','n'])pushMove(moves,pos,from,to,{promotion:pr});else pushMove(moves,pos,from,to)}else if(to===pos.ep)pushMove(moves,pos,from,to,{ep:true,capture:color==='w'?'p':'P'})}}
  else if(t==='n'){for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])if(onBoard(r+dr,c+dc))pushMove(moves,pos,from,(r+dr)*8+c+dc)}
  else if(t==='b'||t==='r'||t==='q'){const dirs=t==='b'?[[-1,-1],[-1,1],[1,-1],[1,1]]:t==='r'?[[-1,0],[1,0],[0,-1],[0,1]]:[[-1,-1],[-1,1],[1,-1],[1,1],[-1,0],[1,0],[0,-1],[0,1]];for(const[dr,dc]of dirs){let rr=r+dr,cc=c+dc;while(onBoard(rr,cc)){const to=rr*8+cc;if(!b[to])pushMove(moves,pos,from,to);else{pushMove(moves,pos,from,to);break}rr+=dr;cc+=dc}}}
  else if(t==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;if(onBoard(r+dr,c+dc))pushMove(moves,pos,from,(r+dr)*8+c+dc)}const enemy=opposite(color);if(color==='w'&&from===60){if(pos.castling.includes('K')&&!b[61]&&!b[62]&&b[63]==='R'&&!attacked(pos,60,enemy)&&!attacked(pos,61,enemy)&&!attacked(pos,62,enemy))moves.push({from:60,to:62,piece:'K',castle:'K'});if(pos.castling.includes('Q')&&!b[59]&&!b[58]&&!b[57]&&b[56]==='R'&&!attacked(pos,60,enemy)&&!attacked(pos,59,enemy)&&!attacked(pos,58,enemy))moves.push({from:60,to:58,piece:'K',castle:'Q'})}if(color==='b'&&from===4){if(pos.castling.includes('k')&&!b[5]&&!b[6]&&b[7]==='r'&&!attacked(pos,4,enemy)&&!attacked(pos,5,enemy)&&!attacked(pos,6,enemy))moves.push({from:4,to:6,piece:'k',castle:'k'});if(pos.castling.includes('q')&&!b[3]&&!b[2]&&!b[1]&&b[0]==='r'&&!attacked(pos,4,enemy)&&!attacked(pos,3,enemy)&&!attacked(pos,2,enemy))moves.push({from:4,to:2,piece:'k',castle:'q'})}}
  }return moves}
function makeMove(pos,move){const n=clonePos(pos),b=n.board,color=pieceColor(move.piece),type=pieceType(move.piece),captured=move.ep?(color==='w'?'p':'P'):b[move.to];b[move.from]=null;if(move.ep){const cap=move.to+(color==='w'?8:-8);b[cap]=null}if(move.castle){if(move.to===62){b[61]=b[63];b[63]=null}else if(move.to===58){b[59]=b[56];b[56]=null}else if(move.to===6){b[5]=b[7];b[7]=null}else if(move.to===2){b[3]=b[0];b[0]=null}}let placed=move.piece;if(move.promotion)placed=color==='w'?move.promotion.toUpperCase():move.promotion.toLowerCase();b[move.to]=placed;let cast=n.castling;if(type==='k')cast=cast.replace(color==='w'?/[KQ]/g:/[kq]/g,'');const rightsBySquare={63:'K',56:'Q',7:'k',0:'q'};if(type==='r'&&rightsBySquare[move.from])cast=cast.replace(rightsBySquare[move.from],'');if(captured&&pieceType(captured)==='r'&&rightsBySquare[move.to])cast=cast.replace(rightsBySquare[move.to],'');n.castling=cast;n.ep=move.double?(move.from+move.to)/2:-1;n.halfmove=(type==='p'||captured)?0:n.halfmove+1;if(color==='b')n.fullmove++;n.turn=opposite(color);return n}
function legalMoves(pos,color=pos.turn){const out=[];for(const m of pseudoMoves(pos,color)){const n=makeMove(pos,m);if(!inCheck(n,color))out.push(m)}return out}
function insufficient(pos){const pieces=[];for(let i=0;i<64;i++){const p=pos.board[i];if(p&&pieceType(p)!=='k')pieces.push({p,i})}if(!pieces.length)return true;if(pieces.some(x=>['p','r','q'].includes(pieceType(x.p))))return false;if(pieces.length===1&&['b','n'].includes(pieceType(pieces[0].p)))return true;if(pieces.every(x=>pieceType(x.p)==='b')){const colors=new Set(pieces.map(x=>{const[r,c]=rc(x.i);return(r+c)%2}));return colors.size===1}return false}
function gameOutcome(pos,historyKeys=[]){const moves=legalMoves(pos,pos.turn);if(!moves.length){if(inCheck(pos,pos.turn))return{type:'checkmate',winner:opposite(pos.turn),text:'كش مات'};return{type:'stalemate',winner:null,text:'تعادل — ستيل ميت'}}if(pos.halfmove>=100)return{type:'fifty',winner:null,text:'تعادل — قاعدة 50 نقلة'};if(insufficient(pos))return{type:'insufficient',winner:null,text:'تعادل — قطع غير كافية للمات'};const key=positionKey(pos),count=historyKeys.filter(x=>x===key).length;if(count>=3)return{type:'repetition',winner:null,text:'تعادل — تكرار الوضع ثلاث مرات'};return null}
function sanForMove(pos,move,allMoves){if(move.castle)return move.to>move.from?'O-O':'O-O-O';const type=pieceType(move.piece),capture=!!move.capture||move.ep;let san='';if(type!=='p'){san=type.toUpperCase();const same=allMoves.filter(m=>m.from!==move.from&&m.to===move.to&&pieceType(m.piece)===type&&pieceColor(m.piece)===pieceColor(move.piece));if(same.length){const f=move.from%8,r=Math.floor(move.from/8),sameFile=same.some(m=>m.from%8===f),sameRank=same.some(m=>Math.floor(m.from/8)===r);san+=!sameFile?String.fromCharCode(97+f):!sameRank?String(8-r):squareName(move.from)}}else if(capture)san+=squareName(move.from)[0];if(capture)san+='x';san+=squareName(move.to);if(move.promotion)san+='='+move.promotion.toUpperCase();const next=makeMove(pos,move),opp=next.turn;if(inCheck(next,opp))san+=legalMoves(next,opp).length?'+' :'#';return san}
function resultToken(result,colors){if(!result||!result.winner)return'1/2-1/2';return result.winner==='w'?'1-0':'0-1'}
function pgnText(room){const g=room.game||{},hist=g.history||[],result=g.result?.winner?resultToken(g.result,g.colors):g.result?'1/2-1/2':'*',white=room.players?.[g.colors?.white]?.name||'White',black=room.players?.[g.colors?.black]?.name||'Black',date=new Date(g.startedAt||Date.now()).toISOString().slice(0,10).replaceAll('-','.');const headers=`[Event "Al Qahwa Chess"]\n[Site "iegy.net"]\n[Date "${date}"]\n[White "${white.replaceAll('"','')}"]\n[Black "${black.replaceAll('"','')}"]\n[Result "${result}"]\n\n`;let body='';for(let i=0;i<hist.length;i+=2)body+=`${Math.floor(i/2)+1}. ${hist[i]?.san||''}${hist[i+1]?` ${hist[i+1].san}`:''} `;return headers+body.trim()+` ${result}`}

// ---------------- Room lifecycle ----------------
async function createRoom(){els.homeMessage.textContent='';const p=getProfile();if(!p.name){els.homeMessage.textContent='اكتب اسمك الأول.';return}saveProfile();await ensureAuth();for(let n=0;n<7;n++){const code=String(Math.floor(100000+Math.random()*900000));if((await get(roomRef(code))).exists())continue;await set(roomRef(code),{hostUid:state.uid,status:'waiting',gameType:'chess',createdAt:nowMs(),players:{[state.uid]:{name:p.name,avatar:p.avatar,connected:true,lastSeen:Date.now()}},settings:{timeControl:Number(els.timeControl.value)||0,colorChoice:els.colorChoice.value||'random'},expiresAt:nowMs()+7*86400000});await enterRoom(code);return}els.homeMessage.textContent='تعذر إنشاء الغرفة، جرّب مرة أخرى.'}
async function joinRoom(code){
  code=(code||'').trim();
  if(!/^\d{6}$/.test(code)){els.homeMessage.textContent='الكود لازم يكون 6 أرقام.';return}
  const p=getProfile();
  if(!p.name){els.homeMessage.textContent='اكتب اسمك الأول.';return}
  saveProfile();await ensureAuth();
  const rr=roomRef(code);
  try{
    const before=await get(rr);
    if(!before.exists()){els.homeMessage.textContent='الغرفة انتهت أو الكود غير موجود.';return}
    const existing=before.val();
    if((existing.gameType||'domino')!=='chess'){els.homeMessage.textContent='الكود ده خاص بلعبة دومينو، مش شطرنج.';return}

    // Re-entering the same room from the same authenticated device is always allowed.
    if(existing.hostUid===state.uid||existing.guestUid===state.uid){
      await update(ref(db,`rooms/${code}/players/${state.uid}`),{name:p.name,avatar:p.avatar,connected:true,lastSeen:Date.now()});
      await enterRoom(code);return
    }
    if(existing.guestUid){els.homeMessage.textContent='غرفة الشطرنج مكتملة بالفعل.';return}

    // Claim only the guest slot atomically. This is intentionally a small transaction:
    // it avoids aborting when Firebase's first local room snapshot is temporarily null.
    const guestRef=ref(db,`rooms/${code}/guestUid`);
    const claim=await runTransaction(guestRef,current=>{
      if(current==null||current===state.uid)return state.uid;
      return;
    },{applyLocally:false});

    if(!claim.committed||claim.snapshot.val()!==state.uid){
      const latest=await get(rr);
      const room=latest.val();
      if(!room)els.homeMessage.textContent='الغرفة انتهت أو الكود غير موجود.';
      else if(room.guestUid&&room.guestUid!==state.uid)els.homeMessage.textContent='غرفة الشطرنج مكتملة بالفعل.';
      else els.homeMessage.textContent='تعذر حجز مكانك في الغرفة. جرّب مرة أخرى.';
      return
    }

    // Once guestUid is ours, the room rules allow us to write our own player data.
    await update(ref(db,`rooms/${code}/players/${state.uid}`),{
      name:p.name,avatar:p.avatar,connected:true,lastSeen:Date.now()
    });
    els.homeMessage.textContent='';
    await enterRoom(code)
  }catch(e){
    console.error('Chess join failed',e);
    els.homeMessage.textContent=e?.code==='PERMISSION_DENIED'?'صلاحيات Firebase منعت الدخول. ارفع ملف database.rules.json الموجود مع النسخة.':'تعذر دخول غرفة الشطرنج. جرّب مرة أخرى.';
  }
}
async function enterRoom(code){state.roomCode=code;localStorage.setItem('chess_room',code);const pres=ref(db,`rooms/${code}/players/${state.uid}/connected`);await set(pres,true);onDisconnect(pres).set(false);state.roomUnsub?.();state.roomUnsub=onValue(roomRef(code),snap=>{const room=snap.val();if(!room){leaveLocal();return}state.room=room;renderRoom(room);handleVoiceSignal(room.voiceCall).catch(console.warn);if(room.hostUid===state.uid&&room.guestUid&&room.status==='waiting'&&!room.game)startGame().catch(console.error)});}
async function startGame(){const r=state.room;if(!r||r.hostUid!==state.uid||!r.guestUid)return;const host=r.hostUid,guest=r.guestUid,choice=r.settings?.colorChoice||'random';let white=host;if(choice==='black')white=guest;else if(choice==='random')white=Math.random()<.5?host:guest;const black=white===host?guest:host,time=Number(r.settings?.timeControl)||0,fen=startFen(),pos=parseFen(fen);await runTransaction(roomRef(),room=>{if(!room||room.status!=='waiting'||room.game)return;room.status='playing';room.game={fen,colors:{white,black},history:[],positionHistory:[positionKey(pos)],lastMove:null,result:null,clocks:{w:time,b:time},turnStartedAt:Date.now(),startedAt:Date.now(),matchNo:1};room.drawOffer=null;room.expiresAt=Date.now()+7*86400000;return room})}
function renderRoom(room){if(!room.guestUid){setView('lobby');renderLobby(room)}else if(room.status==='waiting'&&!room.game){setView('lobby');renderLobby(room)}else{setView('game');renderGame(room)}}
function renderLobby(room){els.lobbyRoomCode.textContent=state.roomCode;els.lobbyPlayers.innerHTML=playerIds(room).map(uid=>{const p=room.players?.[uid]||{};return`<div class="lobby-player"><span class="ava">${p.avatar||'😎'}</span><div><b>${escapeHtml(p.name||'لاعب')}</b><small>${uid===room.hostUid?'منشئ الغرفة':'اللاعب الثاني'}</small></div><span>${p.connected!==false?'🟢':'⚪'}</span></div>`}).join('');els.lobbyStatus.textContent=room.guestUid?'اللاعبان جاهزان — جاري بدء المباراة…':'في انتظار اللاعب الثاني…'}

async function submitMove(move){if(state.reviewFen)return;const now=nowMs();const moveMeta={sound:'move'};const result=await runTransaction(roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const g=room.game,pos=parseFen(g.fen),myColor=g.colors?.white===state.uid?'w':g.colors?.black===state.uid?'b':null;if(!myColor||pos.turn!==myColor)return;const all=legalMoves(pos,myColor),legal=all.find(m=>m.from===move.from&&m.to===move.to&&(m.promotion||null)===(move.promotion||null));if(!legal)return;const time=Number(room.settings?.timeControl)||0;if(time>0){const elapsed=Math.max(0,now-Number(g.turnStartedAt||now)),left=Math.max(0,Number(g.clocks?.[myColor]??time)-elapsed);g.clocks=g.clocks||{w:time,b:time};g.clocks[myColor]=left;if(left<=0){g.result={type:'timeout',winner:opposite(myColor),text:'انتهى الوقت'};room.status='finished';return room}}
 const san=sanForMove(pos,legal,all),next=makeMove(pos,legal),fen=toFen(next),keys=[...(g.positionHistory||[]),positionKey(next)],hist=[...(g.history||[]),{from:legal.from,to:legal.to,piece:legal.piece,capture:legal.capture||null,promotion:legal.promotion||null,san,fenAfter:fen,by:state.uid,at:now}];g.fen=fen;g.history=hist;g.positionHistory=keys;g.lastMove={from:legal.from,to:legal.to,san,by:state.uid,at:now};g.turnStartedAt=now;room.drawOffer=null;const outcome=gameOutcome(next,keys);if(outcome){g.result=outcome;room.status='finished'}room.expiresAt=now+7*86400000;moveMeta.sound=legal.castle?'castle':(legal.capture||legal.ep)?'capture':inCheck(next,next.turn)?'check':'move';return room});if(result.committed){state.selectedSquare=null;state.legalMoves=[];state.reviewFen=null;playSound(moveMeta.sound)}}
async function claimTimeout(){if(state.claimingTimeout)return;state.claimingTimeout=true;const now=nowMs();try{await runTransaction(roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const time=Number(room.settings?.timeControl)||0;if(!time)return;const pos=parseFen(room.game.fen),c=pos.turn,elapsed=Math.max(0,now-Number(room.game.turnStartedAt||now)),left=Math.max(0,Number(room.game.clocks?.[c]??time)-elapsed);if(left>0)return;room.game.clocks[c]=0;room.game.result={type:'timeout',winner:opposite(c),text:'انتهى الوقت'};room.status='finished';return room})}finally{state.claimingTimeout=false}}
async function resign(){if(!state.room||state.room.status!=='playing')return;if(!confirm('متأكد إنك عايز تستسلم؟'))return;await runTransaction(roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const c=room.game.colors.white===state.uid?'w':room.game.colors.black===state.uid?'b':null;if(!c)return;room.game.result={type:'resign',winner:opposite(c),text:'استسلام'};room.status='finished';return room})}
async function offerDraw(){if(!state.room||state.room.status!=='playing')return;await update(roomRef(),{drawOffer:{by:state.uid,at:Date.now()}});toast('تم إرسال عرض التعادل.')}
async function acceptDraw(){await runTransaction(roomRef(),room=>{if(!room||room.status!=='playing'||!room.drawOffer||room.drawOffer.by===state.uid)return;room.game.result={type:'agreement',winner:null,text:'تعادل بالاتفاق'};room.status='finished';room.drawOffer=null;return room})}
async function declineDraw(){if(!state.room?.drawOffer||state.room.drawOffer.by===state.uid)return;await update(roomRef(),{drawOffer:null});toast('تم رفض التعادل.')}
async function rematch(){const now=nowMs();await runTransaction(roomRef(),room=>{if(!room||room.status!=='finished'||!room.game)return;const old=room.game.colors,time=Number(room.settings?.timeControl)||0,fen=startFen(),pos=parseFen(fen);room.status='playing';room.game={fen,colors:{white:old.black,black:old.white},history:[],positionHistory:[positionKey(pos)],lastMove:null,result:null,clocks:{w:time,b:time},turnStartedAt:now,startedAt:now,matchNo:(room.game.matchNo||1)+1};room.drawOffer=null;return room});els.resultModal.classList.add('hidden')}

// ---------------- Rendering & interaction ----------------
function playerCardHtml(p,color,turn){return`<span class="ava">${p?.avatar||'😎'}</span><div><b>${escapeHtml(p?.name||'لاعب')}</b><small>${color==='w'?'الأبيض':'الأسود'}${turn?' • دوره الآن':''}</small></div>`}
function renderGame(room){const g=room.game||{},pos=parseFen(state.reviewFen||g.fen),myColor=playerColor(room),opp=otherUid(room),oppColor=myColor?opposite(myColor):null,my=room.players?.[state.uid],op=room.players?.[opp];els.roomCodeLabel.textContent=state.roomCode;els.myInfo.innerHTML=playerCardHtml(my,myColor,room.status==='playing'&&parseFen(g.fen).turn===myColor);els.opponentInfo.innerHTML=playerCardHtml(op,oppColor,room.status==='playing'&&parseFen(g.fen).turn===oppColor);els.myInfo.classList.toggle('turn',room.status==='playing'&&parseFen(g.fen).turn===myColor);els.opponentInfo.classList.toggle('turn',room.status==='playing'&&parseFen(g.fen).turn===oppColor);renderBoard(pos,myColor,g);renderMoves(room);renderCaptured(room,myColor);renderPromotionChoices(myColor||'w');renderClocks(room);renderDrawOffer(room);renderChat(room);renderVoiceUi();if(room.reaction&&room.reaction.at>state.lastReactionAt){state.lastReactionAt=room.reaction.at;if(room.reaction.by!==state.uid)toast(room.reaction.emoji)};
 const live=parseFen(g.fen),check=inCheck(live,live.turn),myTurn=live.turn===myColor;els.statusBanner.classList.toggle('check',check&&room.status==='playing');els.statusBanner.textContent=room.status==='finished'?'انتهت المباراة':state.reviewFen?'أنت تشاهد نقلة سابقة — اضغط «الحالي» للعودة':check?(myTurn?'كش عليك!':'كش على صاحبك!'):myTurn?'دورك الآن':'دور صاحبك';els.offerDrawBtn.disabled=room.status!=='playing';els.resignBtn.disabled=room.status!=='playing';if(room.status==='finished')showResult(room);else els.resultModal.classList.add('hidden')}
function renderBoard(pos,myColor,g){els.chessBoard.innerHTML='';const orientation=myColor||'w',order=orientation==='w'?[...Array(64).keys()]:[...Array(64).keys()].reverse(),liveFen=state.room?.game?.fen,last=g?.lastMove;const livePos=parseFen(liveFen);const checkSq=inCheck(pos,pos.turn)?kingSquare(pos,pos.turn):-1;for(const i of order){const [r,c]=rc(i),sq=document.createElement('div');sq.className=`square ${(r+c)%2?'dark':'light'}`;sq.dataset.index=i;if(last&&(i===last.from||i===last.to)&&!state.reviewFen)sq.classList.add('last');if(i===state.selectedSquare&&!state.reviewFen)sq.classList.add('selected');const legal=state.legalMoves.filter(m=>m.to===i);if(legal.length&&!state.reviewFen){sq.classList.add('legal');if(pos.board[i]||legal.some(m=>m.ep))sq.classList.add('capture')}if(i===checkSq)sq.classList.add('check');const p=pos.board[i];if(p){const piece=document.createElement('span');piece.className=`piece ${pieceColor(p)==='w'?'white':'black'}`;piece.innerHTML=pieceImgHtml(p);piece.dataset.index=i;if(!state.reviewFen&&state.room?.status==='playing'&&pieceColor(p)===myColor&&livePos.turn===myColor)piece.classList.add('draggable');sq.appendChild(piece)}const file=orientation==='w'?r===7:r===0,rank=orientation==='w'?c===0:c===7;if(file){const x=document.createElement('span');x.className='coord file';x.textContent=String.fromCharCode(97+c);sq.appendChild(x)}if(rank){const x=document.createElement('span');x.className='coord rank';x.textContent=String(8-r);sq.appendChild(x)}els.chessBoard.appendChild(sq)}}
function renderMoves(room){const h=room.game?.history||[];els.moveCount.textContent=`${h.length} نقلة`;els.movesList.innerHTML='';for(let i=0;i<h.length;i+=2){const no=document.createElement('span');no.className='move-no';no.textContent=`${i/2+1}.`;els.movesList.appendChild(no);for(let k=0;k<2;k++){const m=h[i+k],b=document.createElement('button');b.className='move-btn';if(m){b.textContent=m.san;b.title=squareName(m.from)+'-'+squareName(m.to);b.addEventListener('click',()=>{state.reviewFen=m.fenAfter;state.selectedSquare=null;state.legalMoves=[];renderGame(state.room)})}else b.disabled=true;els.movesList.appendChild(b)}}els.livePositionBtn.classList.toggle('hidden',!state.reviewFen)}
function renderCaptured(room,myColor){const h=room.game?.history||[],mine=[],opp=[];for(const m of h){if(!m.capture)continue;const by=room.game.colors.white===m.by?'w':'b';(by===myColor?mine:opp).push(m.capture)}const render=arr=>arr.map(code=>pieceImgHtml(code,'captured-svg')).join('');els.capturedByMe.innerHTML=render(mine);els.capturedByOpponent.innerHTML=render(opp)}
function remainingClock(room,color){const time=Number(room.settings?.timeControl)||0;if(!time)return null;let left=Number(room.game?.clocks?.[color]??time);if(room.status==='playing'&&parseFen(room.game.fen).turn===color)left-=Math.max(0,nowMs()-Number(room.game.turnStartedAt||nowMs()));return Math.max(0,left)}
function clockText(ms){if(ms==null)return'∞';const total=Math.max(0,ms);const m=Math.floor(total/60000),s=Math.floor((total%60000)/1000),t=Math.floor((total%1000)/100);return total<60000?`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${t}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function renderClocks(room){const myColor=playerColor(room),opColor=myColor?opposite(myColor):'b',pos=parseFen(room.game.fen),my=remainingClock(room,myColor),op=remainingClock(room,opColor);els.myClock.textContent=clockText(my);els.opponentClock.textContent=clockText(op);for(const [el,val] of [[els.myClock,my],[els.opponentClock,op]]){el.classList.toggle('low',val!=null&&val<=60000&&val>10000);el.classList.toggle('critical',val!=null&&val<=10000)}els.myClock.classList.toggle('active',room.status==='playing'&&pos.turn===myColor);els.opponentClock.classList.toggle('active',room.status==='playing'&&pos.turn===opColor);if(room.status==='playing'&&Number(room.settings?.timeControl)&&remainingClock(room,pos.turn)<=0)claimTimeout().catch(console.warn)}
function renderDrawOffer(room){const offer=room.drawOffer;els.drawOfferBar.classList.toggle('hidden',!offer||offer.by===state.uid||room.status!=='playing');els.offerDrawBtn.textContent=offer?.by===state.uid?'تم عرض التعادل':'عرض تعادل';els.offerDrawBtn.disabled=room.status!=='playing'||offer?.by===state.uid}
function showResult(room){const r=room.game?.result;if(!r)return;const myColor=playerColor(room),won=r.winner===myColor,lost=r.winner&&r.winner!==myColor;els.resultEmoji.textContent=won?'🏆':lost?'🎯':'🤝';els.resultTitle.textContent=won?'أنت كسبت المباراة!':lost?'صاحبك كسب المباراة':'انتهت بالتعادل';els.resultText.textContent=r.text||'انتهت المباراة';els.resultModal.classList.remove('hidden')}
function chooseSquare(i){if(state.reviewFen||!state.room||state.room.status!=='playing')return;const pos=parseFen(state.room.game.fen),myColor=playerColor(state.room);if(pos.turn!==myColor)return;const p=pos.board[i];if(state.selectedSquare!=null){const moves=state.legalMoves.filter(m=>m.to===i);if(moves.length){const promo=moves.filter(m=>m.promotion);if(promo.length){state.pendingPromotion={moves:promo};els.promotionModal.classList.remove('hidden');return}submitMove(moves[0]);return}}if(p&&pieceColor(p)===myColor){state.selectedSquare=i;state.legalMoves=legalMoves(pos,myColor).filter(m=>m.from===i);renderGame(state.room)}else{state.selectedSquare=null;state.legalMoves=[];renderGame(state.room)}}
function startDrag(e,piece){if(state.reviewFen||!state.room||state.room.status!=='playing')return;const from=Number(piece.dataset.index),pos=parseFen(state.room.game.fen),myColor=playerColor(state.room);if(pos.turn!==myColor||pieceColor(pos.board[from])!==myColor)return;const moves=legalMoves(pos,myColor).filter(m=>m.from===from);if(!moves.length)return;state.selectedSquare=from;state.legalMoves=moves;renderGame(state.room);const ghost=document.createElement('div');ghost.className=`drag-piece ${myColor==='w'?'white':'black'}`;ghost.innerHTML=pieceImgHtml(pos.board[from],'drag-svg');document.body.appendChild(ghost);piece.classList.add('drag-source');state.drag={from,moves,ghost,pointerId:e.pointerId};positionGhost(e);try{piece.setPointerCapture(e.pointerId)}catch{}e.preventDefault()}
function positionGhost(e){if(!state.drag)return;state.drag.ghost.style.left=`${e.clientX}px`;state.drag.ghost.style.top=`${e.clientY}px`}
function endDrag(e){if(!state.drag)return;const d=state.drag,el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.square'),to=el?Number(el.dataset.index):-1,moves=d.moves.filter(m=>m.to===to);d.ghost.remove();state.drag=null;if(moves.length){const promo=moves.filter(m=>m.promotion);if(promo.length){state.pendingPromotion={moves:promo};els.promotionModal.classList.remove('hidden')}else submitMove(moves[0])}else{state.selectedSquare=null;state.legalMoves=[];renderGame(state.room)}}

// ---------------- Chat & reactions ----------------
function chatItems(room){return Object.values(room.chat||{}).filter(Boolean).sort((a,b)=>(a.at||0)-(b.at||0)).slice(-80)}
function renderChat(room){const items=chatItems(room);if(items.length>state.lastChatCount&&!els.chatPanel.classList.contains('hidden')){}else if(items.length>state.lastChatCount){els.chatUnread.textContent=Math.min(9,items.length-state.lastChatCount);els.chatUnread.classList.remove('hidden')}state.lastChatCount=items.length;els.chatMessages.innerHTML=items.map(m=>`<div class="chat-msg ${m.uid===state.uid?'mine':'theirs'}"><small>${m.uid===state.uid?'أنت':escapeHtml(m.name||'صاحبك')}</small>${escapeHtml(m.text||'')}</div>`).join('')||'<div class="chat-msg theirs">ابدأوا الكلام 👋</div>';if(!els.chatPanel.classList.contains('hidden'))requestAnimationFrame(()=>els.chatMessages.scrollTop=els.chatMessages.scrollHeight)}
async function sendChat(text){text=(text||'').trim().slice(0,180);if(!text||!state.roomCode)return;const p=state.room.players?.[state.uid]||getProfile(),key=`${Date.now()}_${Math.random().toString(36).slice(2,7)}`;await set(ref(db,`rooms/${state.roomCode}/chat/${key}`),{uid:state.uid,name:p.name||'لاعب',text,at:Date.now()});els.chatInput.value=''}
async function sendReaction(emoji){if(!state.roomCode)return;await update(roomRef(),{reaction:{emoji,by:state.uid,at:Date.now()}});toast(emoji)}

// ---------------- Voice ----------------
const DEFAULT_ICE=[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}];let rtcConfig=null;
async function getRtcConfig(){if(rtcConfig)return rtcConfig;const extra=Array.isArray(turnConfig?.iceServers)?turnConfig.iceServers:[];rtcConfig={iceServers:[...DEFAULT_ICE,...extra],iceCandidatePoolSize:1,iceTransportPolicy:'all'};return rtcConfig}
function voiceCallRef(){return ref(db,`rooms/${state.roomCode}/voiceCall`)}function candRef(uid,key){return ref(db,`rooms/${state.roomCode}/voiceCall/candidates/${uid}/${key}`)}
async function ensureMic(){if(state.localStream)return state.localStream;state.localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});return state.localStream}
function serDesc(d){return{type:d.type,sdp:d.sdp}}function serCand(c){return{candidate:c.candidate,sdpMid:c.sdpMid,sdpMLineIndex:c.sdpMLineIndex,usernameFragment:c.usernameFragment||null}}
async function writeCand(c){const key=`${Date.now()}_${Math.random().toString(36).slice(2,7)}`;await set(candRef(state.uid,key),serCand(c))}
async function flushIce(){if(!state.voiceSignalReady)return;const q=[...state.pendingIce];state.pendingIce=[];for(const c of q)await writeCand(c).catch(console.warn)}
async function createPeer(){try{state.peer?.close()}catch{}state.seenIce=new Set();state.remoteDescriptionSet=false;state.pendingIce=[];state.voiceSignalReady=false;const pc=new RTCPeerConnection(await getRtcConfig());state.peer=pc;const stream=await ensureMic();stream.getTracks().forEach(t=>pc.addTrack(t,stream));state.remoteStream=new MediaStream();els.remoteAudio.srcObject=state.remoteStream;pc.ontrack=e=>{for(const t of(e.streams?.[0]?.getTracks()||[e.track]))if(!state.remoteStream.getTracks().some(x=>x.id===t.id))state.remoteStream.addTrack(t);els.remoteAudio.play().catch(()=>{})};pc.onicecandidate=e=>{if(!e.candidate)return;state.voiceSignalReady?writeCand(e.candidate).catch(console.warn):state.pendingIce.push(e.candidate)};pc.onconnectionstatechange=()=>{const s=pc.connectionState;els.voiceStatusText.textContent=s==='connected'?'متصل صوتيًا ✅':s==='connecting'?'جاري توصيل الصوت…':s==='disconnected'?'انقطع الصوت مؤقتًا…':s==='failed'?'تعذر الاتصال الصوتي':'اتصال صوتي';if(s==='failed')toast('تعذر الاتصال الصوتي. جرّب الاتصال مرة أخرى.')};return pc}
async function addRemoteCandidates(call){if(!state.peer||!call?.candidates)return;const remote=state.uid===call.callerUid?call.calleeUid:call.callerUid;for(const[key,c]of Object.entries(call.candidates?.[remote]||{})){if(state.seenIce.has(key))continue;try{await state.peer.addIceCandidate(new RTCIceCandidate(c));state.seenIce.add(key)}catch(e){console.warn(e)}}}
async function startVoice(){if(state.currentCallId)return;const callee=otherUid();if(!callee){toast('استنى صاحبك يدخل الأول.');return}try{const id=`${Date.now()}_${state.uid.slice(0,5)}`;state.currentCallId=id;const pc=await createPeer(),offer=await pc.createOffer({offerToReceiveAudio:true});await pc.setLocalDescription(offer);await set(voiceCallRef(),{id,callerUid:state.uid,calleeUid:callee,status:'ringing',offer:serDesc(pc.localDescription),createdAt:nowMs()});state.voiceSignalReady=true;await flushIce();renderVoiceUi()}catch(e){console.error(e);cleanupVoice();toast(e.name==='NotAllowedError'?'اسمح باستخدام الميكروفون.':'تعذر بدء المكالمة.') }}
async function acceptVoice(){const call=state.incomingCall;if(!call||state.processingVoice)return;state.processingVoice=true;try{els.voiceIncomingModal.classList.add('hidden');state.currentCallId=call.id;const pc=await createPeer();state.currentCallId=call.id;await pc.setRemoteDescription(new RTCSessionDescription(call.offer));state.remoteDescriptionSet=true;await addRemoteCandidates(call);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await update(voiceCallRef(),{answer:serDesc(pc.localDescription),status:'answered',answeredAt:Date.now()});state.voiceSignalReady=true;await flushIce();state.incomingCall=null;renderVoiceUi()}catch(e){console.error(e);cleanupVoice();toast('تعذر قبول المكالمة.')}finally{state.processingVoice=false}}
async function declineVoice(){const c=state.incomingCall;els.voiceIncomingModal.classList.add('hidden');state.incomingCall=null;if(c?.id)await update(voiceCallRef(),{status:'declined',endedAt:Date.now()}).catch(()=>{})}
async function handleVoiceSignal(call){if(state.processingVoice)return;if(!call){if(state.currentCallId||state.incomingCall)cleanupVoice(true);return}if(call.status==='ringing'&&call.calleeUid===state.uid&&!state.currentCallId){state.incomingCall=call;els.voiceCallerName.textContent=state.room?.players?.[call.callerUid]?.name||'صاحبك';els.voiceIncomingModal.classList.remove('hidden');return}if(call.status==='declined'&&call.callerUid===state.uid){toast('صاحبك رفض المكالمة.');cleanupVoice();return}if(call.status==='ended'){if(state.currentCallId)toast('تم إنهاء المكالمة.');cleanupVoice(true);return}if(state.currentCallId!==call.id||!state.peer)return;if(call.callerUid===state.uid&&call.answer&&!state.remoteDescriptionSet){await state.peer.setRemoteDescription(new RTCSessionDescription(call.answer)).catch(console.warn);state.remoteDescriptionSet=true}await addRemoteCandidates(call)}
function renderVoiceUi(){els.voiceCallBtn.disabled=!otherUid()||!!state.currentCallId;els.voiceCallLabel.textContent=state.currentCallId?'مشغول':'اتصال';els.voiceActiveBar.classList.toggle('hidden',!state.currentCallId);els.voiceMuteBtn.textContent=state.voiceMuted?'🎙️ تشغيل':'🔇 كتم'}
function toggleMute(){if(!state.localStream)return;state.voiceMuted=!state.voiceMuted;state.localStream.getAudioTracks().forEach(t=>t.enabled=!state.voiceMuted);renderVoiceUi()}
async function hangup(){if(state.roomCode&&state.currentCallId)await update(voiceCallRef(),{status:'ended',endedBy:state.uid,endedAt:Date.now()}).catch(()=>{});cleanupVoice()}
function cleanupVoice(hideIncoming=true){try{state.peer?.close()}catch{}state.peer=null;state.localStream?.getTracks().forEach(t=>t.stop());state.localStream=null;state.remoteStream?.getTracks().forEach(t=>t.stop());state.remoteStream=null;els.remoteAudio.srcObject=null;state.currentCallId=null;state.voiceSignalReady=false;state.pendingIce=[];state.seenIce=new Set();state.remoteDescriptionSet=false;state.voiceMuted=false;if(hideIncoming){state.incomingCall=null;els.voiceIncomingModal.classList.add('hidden')}renderVoiceUi()}

// ---------------- Utilities ----------------
function playSound(type){if(!state.sound)return;const map={move:'./assets/chess-move.wav?v=7.3.0',capture:'./assets/chess-capture.wav?v=7.3.0',castle:'./assets/chess-castle.wav?v=7.3.0',check:'./assets/chess-check.wav?v=7.3.0'};const src=map[type]||map.move;try{const audio=(state.audio[type]||state.audio.move)?.cloneNode?.()||new Audio(src);audio.volume=type==='check'?0.62:0.55;audio.currentTime=0;audio.play().catch(()=>{});}catch{}}
async function shareRoom(){const url=new URL('./chess.html',location.href);url.searchParams.set('room',state.roomCode);const text=`تعالى نلعب شطرنج على القهوة — كود الغرفة ${state.roomCode}`;if(navigator.share){try{await navigator.share({title:'القهوة — شطرنج',text,url:url.href});return}catch{}}await navigator.clipboard.writeText(url.href);toast('تم نسخ رابط المباراة.')}
async function copyCode(){await navigator.clipboard.writeText(state.roomCode);toast('تم نسخ الكود.')}
function leaveLocal(){state.roomUnsub?.();state.roomUnsub=null;cleanupVoice();state.roomCode=null;state.room=null;state.reviewFen=null;localStorage.removeItem('chess_room');location.href='./'}
async function downloadPgn(){if(!state.room)return;const blob=new Blob([pgnText(state.room)],{type:'application/x-chess-pgn;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`alqahwa-${state.roomCode||'chess'}.pgn`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

// ---------------- Events ----------------
els.avatarPicker.addEventListener('click',e=>{const b=e.target.closest('button[data-avatar]');if(!b)return;state.selectedAvatar=b.dataset.avatar;els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b))});
els.createRoomBtn.addEventListener('click',createRoom);els.showJoinBtn.addEventListener('click',()=>els.joinBox.classList.toggle('hidden'));els.joinRoomBtn.addEventListener('click',()=>joinRoom(els.roomCodeInput.value));els.roomCodeInput.addEventListener('keydown',e=>e.key==='Enter'&&joinRoom(els.roomCodeInput.value));els.copyCodeBtn.addEventListener('click',copyCode);els.shareRoomBtn.addEventListener('click',shareRoom);els.shareInGameBtn.addEventListener('click',shareRoom);els.leaveLobbyBtn.addEventListener('click',leaveLocal);els.offerDrawBtn.addEventListener('click',offerDraw);els.acceptDrawBtn.addEventListener('click',acceptDraw);els.declineDrawBtn.addEventListener('click',declineDraw);els.resignBtn.addEventListener('click',resign);els.rematchBtn.addEventListener('click',rematch);els.resultHomeBtn.addEventListener('click',leaveLocal);els.livePositionBtn.addEventListener('click',()=>{state.reviewFen=null;renderGame(state.room)});els.downloadPgnBtn.addEventListener('click',downloadPgn);els.soundBtn.addEventListener('click',()=>{state.sound=!state.sound;localStorage.setItem('chess_sound',state.sound?'1':'0');els.soundBtn.textContent=state.sound?'🔊':'🔇'});
els.chessBoard.addEventListener('click',e=>{if(state.drag)return;const sq=e.target.closest('.square');if(sq)chooseSquare(Number(sq.dataset.index))});
els.chessBoard.addEventListener('pointerdown',e=>{const p=e.target.closest('.piece.draggable');if(p)startDrag(e,p)});window.addEventListener('pointermove',e=>{if(state.drag){positionGhost(e);e.preventDefault()}});window.addEventListener('pointerup',e=>{if(state.drag)endDrag(e)});
els.promotionChoices.addEventListener('click',e=>{const b=e.target.closest('button[data-piece]');if(!b||!state.pendingPromotion)return;const m=state.pendingPromotion.moves.find(x=>x.promotion===b.dataset.piece);state.pendingPromotion=null;els.promotionModal.classList.add('hidden');if(m)submitMove(m)});
els.chatToggleBtn.addEventListener('click',()=>{els.chatPanel.classList.toggle('hidden');els.chatUnread.classList.add('hidden');requestAnimationFrame(()=>els.chatMessages.scrollTop=els.chatMessages.scrollHeight)});els.chatCloseBtn.addEventListener('click',()=>els.chatPanel.classList.add('hidden'));els.chatForm.addEventListener('submit',e=>{e.preventDefault();sendChat(els.chatInput.value)});els.reactions.addEventListener('click',e=>{const b=e.target.closest('button');if(b)sendReaction(b.textContent.trim())});els.voiceCallBtn.addEventListener('click',startVoice);els.voiceAcceptBtn.addEventListener('click',acceptVoice);els.voiceDeclineBtn.addEventListener('click',declineVoice);els.voiceMuteBtn.addEventListener('click',toggleMute);els.voiceHangupBtn.addEventListener('click',hangup);

setInterval(()=>{if(state.room?.game&&els.gameView.classList.contains('active'))renderClocks(state.room)},100);

els.boardThemeChoice?.addEventListener('change',()=>setVisualTheme('board',els.boardThemeChoice.value));
els.gameBoardThemeChoice?.addEventListener('change',()=>setVisualTheme('board',els.gameBoardThemeChoice.value));
els.pieceThemeChoice?.addEventListener('change',()=>setVisualTheme('piece',els.pieceThemeChoice.value));
els.gamePieceThemeChoice?.addEventListener('change',()=>setVisualTheme('piece',els.gamePieceThemeChoice.value));

(async function boot(){state.sound=localStorage.getItem('chess_sound')!=='0';els.soundBtn.textContent=state.sound?'🔊':'🔇';const n=localStorage.getItem('coffee_name');if(n)els.playerName.value=n;const a=localStorage.getItem('coffee_avatar')||'😎';state.selectedAvatar=a;els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===a));els.timeControl.value=localStorage.getItem('chess_time')||'0';els.colorChoice.value=localStorage.getItem('chess_color')||'random';els.boardThemeChoice.value=localStorage.getItem('chess_board_theme')||'classic';els.pieceThemeChoice.value=normalizePieceTheme(localStorage.getItem('chess_piece_theme')||'classic');syncThemeControls();applyVisualThemes();renderPromotionChoices('w');renderMiniBoard();preloadSound('move','./assets/chess-move.wav?v=7.3.0');preloadSound('capture','./assets/chess-capture.wav?v=7.3.0');preloadSound('castle','./assets/chess-castle.wav?v=7.3.0');preloadSound('check','./assets/chess-check.wav?v=7.3.0');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=7.3.0').catch(console.warn);try{await ensureAuth();onValue(ref(db,'.info/serverTimeOffset'),snap=>{state.serverOffset=Number(snap.val()||0)});const urlRoom=new URL(location.href).searchParams.get('room'),saved=localStorage.getItem('chess_room'),candidate=urlRoom||saved;if(candidate&&/^\d{6}$/.test(candidate)){
  const snap=await get(roomRef(candidate));
  if(snap.exists()){
    const r=snap.val();
    if((r.gameType||'domino')!=='chess'){
      els.homeMessage.textContent='الكود ده خاص بلعبة دومينو.'
    }else{
      const mine=[r.hostUid,r.guestUid].includes(state.uid);
      if(mine) await enterRoom(candidate);
      else if(urlRoom){
        els.roomCodeInput.value=candidate;els.joinBox.classList.remove('hidden');
        if(!r.guestUid){
          if((els.playerName.value||'').trim()) await joinRoom(candidate);
          else els.homeMessage.textContent='اكتب اسمك ثم اضغط دخول للانضمام للمباراة.';
        }else els.homeMessage.textContent='غرفة الشطرنج مكتملة بالفعل.';
      }
    }
  }else if(urlRoom){
    els.roomCodeInput.value=candidate;els.joinBox.classList.remove('hidden');
    els.homeMessage.textContent='الغرفة انتهت أو الكود غير موجود.';
  }
}}catch(e){console.error(e);els.homeMessage.textContent='تعذر الاتصال بـ Firebase.'}})();
