(()=>{
const $=id=>document.getElementById(id),boardEl=$('board2048'),scoreEl=$('score'),bestEl=$('bestScore'),newBtn=$('newGameBtn'),undoBtn=$('undoBtn'),soundBtn=$('soundBtn'),msg=$('gameMessage'),msgTitle=$('messageTitle'),msgText=$('messageText'),msgEmoji=$('messageEmoji'),continueBtn=$('continueBtn'),restartBtn=$('restartBtn'),fx=$('fxLayer');
const state={grid:Array(16).fill(0),score:0,best:Number(localStorage.getItem('coffee_2048_best')||0),sound:localStorage.getItem('coffee_2048_sound')!=='0',history:null,wonShown:false,lastSpawn:-1,lastMerged:new Set()};
const audio={move:new Audio('./assets/2048-move.wav?v=8.1.0'),merge:new Audio('./assets/2048-merge.wav?v=8.1.0'),win:new Audio('./assets/2048-win.wav?v=8.1.0'),gameover:new Audio('./assets/2048-gameover.wav?v=8.1.0')};Object.values(audio).forEach(a=>a.preload='auto');
function play(k){if(!state.sound)return;try{const a=audio[k].cloneNode();a.volume=k==='move'?.38:.58;a.play().catch(()=>{})}catch{}}
function updateSound(){soundBtn.textContent=state.sound?'🔊':'🔇'}
function save(){localStorage.setItem('coffee_2048_save',JSON.stringify({grid:state.grid,score:state.score,wonShown:state.wonShown}));localStorage.setItem('coffee_2048_best',String(state.best))}
function load(){try{const x=JSON.parse(localStorage.getItem('coffee_2048_save')||'null');if(x?.grid?.length===16){state.grid=x.grid.map(Number);state.score=Number(x.score)||0;state.wonShown=!!x.wonShown;return true}}catch{}return false}
function empty(){return state.grid.map((v,i)=>v?null:i).filter(v=>v!==null)}
function spawn(){const e=empty();if(!e.length)return;const i=e[Math.floor(Math.random()*e.length)];state.grid[i]=Math.random()<.9?2:4;state.lastSpawn=i}
function newGame(){state.grid=Array(16).fill(0);state.score=0;state.history=null;state.wonShown=false;state.lastMerged=new Set();spawn();spawn();hideMessage();save();render()}
function snapshot(){state.history={grid:[...state.grid],score:state.score,wonShown:state.wonShown}}
function undo(){if(!state.history)return;state.grid=[...state.history.grid];state.score=state.history.score;state.wonShown=state.history.wonShown;state.history=null;state.lastSpawn=-1;state.lastMerged=new Set();save();render()}
function compress(line){const vals=line.filter(Boolean),out=[],merged=[];let gain=0;for(let i=0;i<vals.length;i++){if(vals[i]===vals[i+1]){const v=vals[i]*2;out.push(v);merged.push(out.length-1);gain+=v;i++}else out.push(vals[i])}while(out.length<4)out.push(0);return{out,gain,merged}}
function arraysEqual(a,b){return a.every((v,i)=>v===b[i])}
function move(dir){const before=[...state.grid],priorHistory=state.history;snapshot();let next=[...state.grid],gain=0,mergedIndexes=new Set();
 const get=(r,c)=>state.grid[r*4+c],set=(r,c,v)=>{next[r*4+c]=v};
 if(dir==='left'||dir==='right'){for(let r=0;r<4;r++){let line=[0,1,2,3].map(c=>get(r,c));if(dir==='right')line.reverse();const z=compress(line);gain+=z.gain;let out=z.out;if(dir==='right')out=[...out].reverse();for(let c=0;c<4;c++)set(r,c,out[c]);z.merged.forEach(mi=>{const c=dir==='right'?3-mi:mi;mergedIndexes.add(r*4+c)})}}
 else{for(let c=0;c<4;c++){let line=[0,1,2,3].map(r=>get(r,c));if(dir==='down')line.reverse();const z=compress(line);gain+=z.gain;let out=z.out;if(dir==='down')out=[...out].reverse();for(let r=0;r<4;r++)set(r,c,out[r]);z.merged.forEach(mi=>{const r=dir==='down'?3-mi:mi;mergedIndexes.add(r*4+c)})}}
 if(arraysEqual(before,next)){state.history=priorHistory;render();return}state.grid=next;state.score+=gain;state.best=Math.max(state.best,state.score);state.lastMerged=mergedIndexes;spawn();save();play(gain?'merge':'move');if(gain)burst();render();checkState()}
function canMove(){if(empty().length)return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const v=state.grid[r*4+c];if(c<3&&v===state.grid[r*4+c+1])return true;if(r<3&&v===state.grid[(r+1)*4+c])return true}return false}
function checkState(){if(!state.wonShown&&state.grid.some(v=>v>=2048)){state.wonShown=true;save();play('win');showMessage('🏆','وصلت لـ2048!','ممتاز! تقدر تكمل وتحقق رقم أكبر أو تبدأ لعبة جديدة.',true);burst(true)}else if(!canMove()){play('gameover');showMessage('☕','انتهت اللعبة',`نتيجتك ${state.score.toLocaleString('ar-EG')}. جرّب تكسر رقمك القياسي!`,false)}}
function showMessage(emoji,title,text,canContinue){msgEmoji.textContent=emoji;msgTitle.textContent=title;msgText.textContent=text;continueBtn.classList.toggle('hidden',!canContinue);msg.classList.remove('hidden')}
function hideMessage(){msg.classList.add('hidden')}
function burst(big=false){const n=big?36:12;for(let i=0;i<n;i++){const s=document.createElement('i');s.className='spark';s.style.left=(45+Math.random()*10)+'%';s.style.top=(42+Math.random()*10)+'%';s.style.setProperty('--dx',`${(Math.random()-.5)*(big?420:180)}px`);s.style.setProperty('--dy',`${(Math.random()-.5)*(big?380:160)}px`);s.style.background=['#efc766','#66d0b2','#f4e3b8','#e58c58'][i%4];fx.appendChild(s);setTimeout(()=>s.remove(),900)}}
function render(){boardEl.innerHTML='';state.grid.forEach((v,i)=>{const d=document.createElement('div');d.className='tile';if(i===state.lastSpawn)d.classList.add('spawn');if(state.lastMerged.has(i))d.classList.add('merge');if(v){d.dataset.v=String(v);d.textContent=v;if(v>2048)d.classList.add('super')}boardEl.appendChild(d)});scoreEl.textContent=state.score.toLocaleString('ar-EG');bestEl.textContent=state.best.toLocaleString('ar-EG');undoBtn.disabled=!state.history;state.lastSpawn=-1;state.lastMerged=new Set();updateSound()}
let sx=0,sy=0;boardEl.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;boardEl.setPointerCapture?.(e.pointerId)});boardEl.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))});window.addEventListener('keydown',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(m){e.preventDefault();move(m)}});
newBtn.onclick=()=>{if(confirm('تبدأ لعبة جديدة؟'))newGame()};restartBtn.onclick=newGame;continueBtn.onclick=hideMessage;undoBtn.onclick=undo;soundBtn.onclick=()=>{state.sound=!state.sound;localStorage.setItem('coffee_2048_sound',state.sound?'1':'0');updateSound()};
if(!load())newGame();else{render();checkState()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=8.1.0').catch(()=>{});
})();
