import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, onValue, runTransaction } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js?v=8.0.0";
import { makeRoomController } from "./room-helper.js?v=8.0.0";
import { createSocial } from "./social.js?v=8.0.0";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=id=>document.getElementById(id);
const els={homeView:$('homeView'),lobbyView:$('lobbyView'),gameView:$('gameView'),playerName:$('playerName'),avatarPicker:$('avatarPicker'),captureBonus:$('captureBonus'),create:$('createRoomBtn'),showJoin:$('showJoinBtn'),joinBox:$('joinBox'),roomCodeInput:$('roomCodeInput'),join:$('joinRoomBtn'),copy:$('copyCodeBtn'),share:$('shareRoomBtn'),leaveLobby:$('leaveLobbyBtn'),roomCodeLabel:$('roomCodeLabel'),status:$('statusBanner'),board:$('ludoBoard'),track:$('trackLayer'),tokenLayer:$('tokenLayer'),redHome:$('redHome'),blueHome:$('blueHome'),dice:$('diceBtn'),diceFace:$('diceFace'),diceHint:$('diceHint'),myInfo:$('myInfo'),oppInfo:$('opponentInfo'),shareGame:$('shareInGameBtn'),rematch:$('rematchBtn'),leaveGame:$('leaveGameBtn'),connection:$('connectionBadge'),reconnect:$('reconnectBanner'),toast:$('toast')};
const state={uid:null,roomCode:null,room:null,roomUnsub:null,avatar:'😎',boardBuilt:false};
const START={r:0,b:26},SAFE=new Set([0,8,13,21,26,34,39,47]),DICE=['⚀','⚁','⚂','⚃','⚄','⚅'];
function setView(n){['home','lobby','game'].forEach(x=>els[x+'View'].classList.toggle('active',x===n))}
function toast(t){els.toast.textContent=t;els.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add('hidden'),1900)}
function profile(){return{name:(els.playerName.value||'').trim().slice(0,18),avatar:state.avatar}}
function settings(){return{captureBonus:els.captureBonus.value==='1'}}
function otherUid(r=state.room){return r?(r.hostUid===state.uid?r.guestUid:r.hostUid):null}
function colorOf(r=state.room,uid=state.uid){return r?.game?.colors?.r===uid?'r':r?.game?.colors?.b===uid?'b':null}
function opponent(c){return c==='r'?'b':'r'}
function globalIndex(c,p){return p>=0&&p<=51?(START[c]+p)%52:null}
function opponentAt(g,c,gi){const oc=opponent(c);return(g.tokens?.[oc]||[]).filter(p=>p>=0&&p<=51&&globalIndex(oc,p)===gi).length}
function legalToken(g,c,p,d){if(p===57)return false;if(p<0){if(d!==6)return false;return opponentAt(g,c,START[c])<2}if(p+d>57)return false;if(p<=51){const steps=Math.min(d,52-p);for(let k=1;k<=steps;k++){const gi=globalIndex(c,p+k);if(gi!=null&&opponentAt(g,c,gi)>=2)return false}}return true}
function legalTokens(g,c){const d=g.dice;if(!d)return[];return(g.tokens?.[c]||[]).map((p,i)=>legalToken(g,c,p,d)?i:-1).filter(i=>i>=0)}
function playerCard(p,c,turn){return`<span class="ava">${p?.avatar||'😎'}</span><div><b>${p?.name||'لاعب'}</b><small>${c==='r'?'الأحمر':'الأزرق'}${turn?' • دوره الآن':''}</small></div>`}
function randomDie(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%6+1}
async function startGame(r){if(!r||r.hostUid!==state.uid||!r.guestUid)return;const red=Math.random()<.5?r.hostUid:r.guestUid,blue=red===r.hostUid?r.guestUid:r.hostUid,turn=Math.random()<.5?'r':'b';await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='waiting'||room.game)return;room.status='playing';room.game={colors:{r:red,b:blue},tokens:{r:[-1,-1,-1,-1],b:[-1,-1,-1,-1]},turn,dice:null,winner:null,moveNo:0,lastMove:null,matchNo:1,startedAt:Date.now()};return room})}
async function roll(){await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const g=room.game,c=colorOf(room,state.uid);if(g.turn!==c||g.dice)return;g.dice=randomDie();g.lastRoll={by:c,dice:g.dice,at:Date.now()};const legal=legalTokens(g,c);if(!legal.length){if(g.dice!==6)g.turn=opponent(c);g.dice=null}return room});els.dice.classList.remove('roll');void els.dice.offsetWidth;els.dice.classList.add('roll')}
async function moveToken(idx){let captured=false;await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const g=room.game,c=colorOf(room,state.uid),d=g.dice;if(g.turn!==c||!d||!legalTokens(g,c).includes(idx))return;const from=g.tokens[c][idx],to=from<0?0:from+d;g.tokens[c][idx]=to;captured=false;if(to<=51){const gi=globalIndex(c,to);if(!SAFE.has(gi)){const oc=opponent(c);for(let j=0;j<g.tokens[oc].length;j++){const op=g.tokens[oc][j];if(op>=0&&op<=51&&globalIndex(oc,op)===gi){g.tokens[oc][j]=-1;captured=true}}}}g.moveNo=(g.moveNo||0)+1;g.lastMove={c,idx,from,to,dice:d,captured,at:Date.now()};if(g.tokens[c].every(x=>x===57)){g.winner=c;room.status='finished';g.dice=null;return room}const extra=d===6||(captured&&room.settings?.captureBonus!==false);g.turn=extra?c:opponent(c);g.dice=null;return room})}
async function rematch(){await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='finished'||!room.game)return;const old=room.game.colors,turn=Math.random()<.5?'r':'b';room.status='playing';room.game={colors:{r:old.b,b:old.r},tokens:{r:[-1,-1,-1,-1],b:[-1,-1,-1,-1]},turn,dice:null,winner:null,moveNo:0,lastMove:null,matchNo:(room.game.matchNo||1)+1,startedAt:Date.now()};return room})}
function trackCoords(){const out=[];const lo=8,hi=92,span=hi-lo;for(let i=0;i<13;i++)out.push({x:lo+span*(i/13),y:lo});for(let i=0;i<13;i++)out.push({x:hi,y:lo+span*(i/13)});for(let i=0;i<13;i++)out.push({x:hi-span*(i/13),y:hi});for(let i=0;i<13;i++)out.push({x:lo,y:hi-span*(i/13)});return out}
const TRACK=trackCoords();
function laneCoords(c){const s=TRACK[START[c]],cx=50,cy=50;return Array.from({length:6},(_,i)=>{const t=(i+1)/7;return{x:s.x+(cx-s.x)*t,y:s.y+(cy-s.y)*t}})}
const LANES={r:laneCoords('r'),b:laneCoords('b')};
function buildBoard(){if(state.boardBuilt)return;state.boardBuilt=true;TRACK.forEach((p,i)=>{const n=document.createElement('div');n.className='track-node';if(SAFE.has(i))n.classList.add('safe');if(i===0)n.classList.add('start-red');if(i===26)n.classList.add('start-blue');n.style.left=p.x+'%';n.style.top=p.y+'%';els.track.appendChild(n)});for(const c of['r','b'])LANES[c].forEach(p=>{const n=document.createElement('div');n.className=`home-lane ${c==='r'?'red':'blue'}`;n.style.left=p.x+'%';n.style.top=p.y+'%';els.track.appendChild(n)});for(const yard of[els.redHome,els.blueHome])for(let i=0;i<4;i++){const s=document.createElement('div');s.className='home-spot';yard.appendChild(s)}}
function homePos(c,i){const bases=c==='r'?[{x:17,y:17},{x:29,y:17},{x:17,y:29},{x:29,y:29}]:[{x:71,y:71},{x:83,y:71},{x:71,y:83},{x:83,y:83}];return bases[i]}
function finishPos(c,i){const a=(c==='r'?210:30)+i*10,r=5.5*Math.PI/180,x=50+Math.cos(a*Math.PI/180)*(5+i*.5),y=50+Math.sin(a*Math.PI/180)*(5+i*.5);return{x,y}}
function tokenPos(c,p,i){if(p<0)return homePos(c,i);if(p<=51)return TRACK[globalIndex(c,p)];if(p<=56)return LANES[c][p-52];return finishPos(c,i)}
function render(room){state.room=room;buildBoard();const g=room.game;if(!g)return;const me=colorOf(room),oc=opponent(me),ouid=otherUid(room);els.roomCodeLabel.textContent=state.roomCode;els.myInfo.innerHTML=playerCard(room.players?.[state.uid],me,room.status==='playing'&&g.turn===me);els.oppInfo.innerHTML=playerCard(room.players?.[ouid],oc,room.status==='playing'&&g.turn===oc);els.myInfo.classList.toggle('turn',room.status==='playing'&&g.turn===me);els.oppInfo.classList.toggle('turn',room.status==='playing'&&g.turn===oc);els.tokenLayer.innerHTML='';const valid=new Set(room.status==='playing'&&g.turn===me&&g.dice?legalTokens(g,me):[]);const occupied={};for(const c of['r','b'])g.tokens[c].forEach((p,i)=>{const pos=tokenPos(c,p,i),key=`${Math.round(pos.x*10)}:${Math.round(pos.y*10)}`,slot=occupied[key]||0;occupied[key]=slot+1;const shifts=[[0,0],[-1.15,-1.0],[1.15,1.0],[-1.1,1.1],[1.1,-1.1]],shift=shifts[Math.min(slot,shifts.length-1)],t=document.createElement('button');t.className=`token ${c==='r'?'red':'blue'}`;t.style.left=(pos.x+shift[0])+'%';t.style.top=(pos.y+shift[1])+'%';if(c===me&&valid.has(i)){t.classList.add('valid');t.addEventListener('click',()=>moveToken(i))}else t.disabled=true;els.tokenLayer.appendChild(t)});els.dice.disabled=room.status!=='playing'||g.turn!==me||!!g.dice;els.diceFace.textContent=g.dice?DICE[g.dice-1]:(g.lastRoll?.dice?DICE[g.lastRoll.dice-1]:'🎲');if(room.status==='finished'){els.status.textContent=g.winner===me?'🏆 كسبت اللودو!':'صاحبك كسب اللودو';els.diceHint.textContent='انتهت المباراة';els.rematch.disabled=false}else if(g.turn!==me){els.status.textContent='دور صاحبك';els.diceHint.textContent='استنى رمية صاحبك';els.rematch.disabled=true}else if(g.dice){els.status.textContent=`طلعت ${g.dice} — اختار حجر`;els.diceHint.textContent=valid.size?'اختار حجر من المضيئين':'لا توجد نقلة متاحة'}else{els.status.textContent='دورك — ارمِ الزهر';els.diceHint.textContent='اضغط على الزهر';els.rematch.disabled=true}social.render(room)}
const ctrl=makeRoomController({db,auth,state,gameType:'ludo',getProfile:profile,getSettings:settings,setView,onRoom:render,onHostReady:startGame,toast});const social=createSocial({db,state,getProfile:profile,toast});
onValue(ref(db,'.info/connected'),s=>{const ok=s.val()===true;els.connection.textContent=ok?'متصل':'غير متصل';els.connection.classList.toggle('offline',!ok);els.reconnect.classList.toggle('hidden',ok)});
els.avatarPicker.addEventListener('click',e=>{const b=e.target.closest('button[data-avatar]');if(!b)return;state.avatar=b.dataset.avatar;els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));localStorage.setItem('coffee_avatar',state.avatar)});els.create.addEventListener('click',()=>{localStorage.setItem('coffee_name',profile().name);localStorage.setItem('ludo_capture_bonus',els.captureBonus.value);ctrl.createRoom()});els.showJoin.addEventListener('click',()=>els.joinBox.classList.toggle('hidden'));els.join.addEventListener('click',()=>ctrl.joinRoom(els.roomCodeInput.value));els.roomCodeInput.addEventListener('keydown',e=>e.key==='Enter'&&ctrl.joinRoom(els.roomCodeInput.value));els.dice.addEventListener('click',roll);els.rematch.addEventListener('click',rematch);els.leaveLobby.addEventListener('click',()=>{social.cleanup();ctrl.leaveLocal()});els.leaveGame.addEventListener('click',()=>{social.cleanup();ctrl.leaveLocal()});async function share(){const u=new URL('./ludo.html',location.href);u.searchParams.set('room',state.roomCode);if(navigator.share){try{return await navigator.share({title:'القهوة — لودو',text:`تعالى نلعب لودو — كود ${state.roomCode}`,url:u.href})}catch{}}await navigator.clipboard.writeText(u.href);toast('تم نسخ الرابط')}els.copy.addEventListener('click',()=>navigator.clipboard.writeText(state.roomCode).then(()=>toast('تم نسخ الكود')));els.share.addEventListener('click',share);els.shareGame.addEventListener('click',share);
(async()=>{els.playerName.value=localStorage.getItem('coffee_name')||'';state.avatar=localStorage.getItem('coffee_avatar')||'😎';els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===state.avatar));els.captureBonus.value=localStorage.getItem('ludo_capture_bonus')||'1';if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=8.0.0').catch(()=>{});await ctrl.resume()})().catch(console.error);
