import { signInAnonymously } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { ref, set, get, update, onValue, runTransaction, onDisconnect } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";

export function makeRoomController({db,auth,state,gameType,getProfile,getSettings,setView,onRoom,onHostReady,toast}){
  const $=id=>document.getElementById(id);
  const els={homeMessage:$('homeMessage'),lobbyRoomCode:$('lobbyRoomCode'),lobbyPlayers:$('lobbyPlayers'),lobbyStatus:$('lobbyStatus'),roomCodeInput:$('roomCodeInput')};
  const roomRef=(code=state.roomCode)=>ref(db,`rooms/${code}`);
  async function ensureAuth(){if(!auth.currentUser)await signInAnonymously(auth);state.uid=auth.currentUser.uid;return state.uid}
  function playerIds(room){return[room.hostUid,room.guestUid].filter(Boolean)}
  function renderLobby(room){if(els.lobbyRoomCode)els.lobbyRoomCode.textContent=state.roomCode;if(els.lobbyPlayers)els.lobbyPlayers.innerHTML=playerIds(room).map(uid=>{const p=room.players?.[uid]||{};return`<div class="lobby-player"><span class="ava">${p.avatar||'😎'}</span><div><b>${String(p.name||'لاعب').replace(/[<>]/g,'')}</b><small>${uid===room.hostUid?'منشئ الغرفة':'اللاعب الثاني'}</small></div><span>${p.connected!==false?'🟢':'⚪'}</span></div>`}).join('');if(els.lobbyStatus)els.lobbyStatus.textContent=room.guestUid?'اللاعبان جاهزان — جاري بدء المباراة…':'في انتظار اللاعب الثاني…'}
  async function createRoom(){if(els.homeMessage)els.homeMessage.textContent='';const p=getProfile();if(!p.name){if(els.homeMessage)els.homeMessage.textContent='اكتب اسمك الأول.';return}await ensureAuth();for(let n=0;n<8;n++){const code=String(Math.floor(100000+Math.random()*900000));if((await get(roomRef(code))).exists())continue;const now=Date.now();await set(roomRef(code),{hostUid:state.uid,status:'waiting',gameType,createdAt:now,players:{[state.uid]:{name:p.name,avatar:p.avatar,connected:true,lastSeen:now}},settings:getSettings?.()||{},expiresAt:now+7*86400000});await enterRoom(code);return}if(els.homeMessage)els.homeMessage.textContent='تعذر إنشاء الغرفة، جرّب مرة أخرى.'}
  async function joinRoom(raw){const code=String(raw||'').trim();if(els.homeMessage)els.homeMessage.textContent='';if(!/^\d{6}$/.test(code)){if(els.homeMessage)els.homeMessage.textContent='الكود لازم يكون 6 أرقام.';return false}const p=getProfile();if(!p.name){if(els.homeMessage)els.homeMessage.textContent='اكتب اسمك الأول.';return false}await ensureAuth();try{const rr=roomRef(code),snap=await get(rr);if(!snap.exists()){if(els.homeMessage)els.homeMessage.textContent='الغرفة غير موجودة أو انتهت.';return false}let room=snap.val();if((room.gameType||'domino')!==gameType){if(els.homeMessage)els.homeMessage.textContent='الكود ده خاص بلعبة تانية.';return false}if(room.hostUid===state.uid||room.guestUid===state.uid){await enterRoom(code);return true}if(room.guestUid){if(els.homeMessage)els.homeMessage.textContent='الغرفة مكتملة بالفعل.';return false}const guestRef=ref(db,`rooms/${code}/guestUid`);const claim=await runTransaction(guestRef,current=>current==null||current===state.uid?state.uid:undefined,{applyLocally:false});if(!claim.committed||claim.snapshot.val()!==state.uid){if(els.homeMessage)els.homeMessage.textContent='الغرفة امتلأت قبل دخولك بلحظات.';return false}const now=Date.now();await update(rr,{[`players/${state.uid}`]:{name:p.name,avatar:p.avatar,connected:true,lastSeen:now},expiresAt:now+7*86400000});await enterRoom(code);return true}catch(e){console.error(gameType,'join',e);if(els.homeMessage)els.homeMessage.textContent=e?.code==='PERMISSION_DENIED'?'صلاحيات Firebase منعت الدخول.':'تعذر دخول الغرفة. جرّب مرة أخرى.';return false}}
  async function enterRoom(code){state.roomCode=code;localStorage.setItem(`${gameType}_room`,code);const pres=ref(db,`rooms/${code}/players/${state.uid}/connected`);await set(pres,true).catch(()=>{});onDisconnect(pres).set(false);state.roomUnsub?.();state.roomUnsub=onValue(roomRef(code),snap=>{const room=snap.val();if(!room){leaveLocal();return}state.room=room;if(!room.guestUid||room.status==='waiting'&&!room.game){setView('lobby');renderLobby(room)}else setView('game');onRoom?.(room);if(room.hostUid===state.uid&&room.guestUid&&room.status==='waiting'&&!room.game)onHostReady?.(room)});}
  function leaveLocal(){state.roomUnsub?.();state.roomUnsub=null;state.roomCode=null;state.room=null;localStorage.removeItem(`${gameType}_room`);location.href='./'}
  async function resume(){await ensureAuth();const params=new URL(location.href).searchParams,urlRoom=params.get('room'),saved=localStorage.getItem(`${gameType}_room`),candidate=urlRoom||saved;if(!candidate||!/^\d{6}$/.test(candidate))return false;const snap=await get(roomRef(candidate));if(!snap.exists())return false;const room=snap.val();if((room.gameType||'domino')!==gameType)return false;if([room.hostUid,room.guestUid].includes(state.uid)){await enterRoom(candidate);return true}if(urlRoom){if(els.roomCodeInput)els.roomCodeInput.value=candidate;const joinBox=$('joinBox');joinBox?.classList.remove('hidden')}return false}
  return{createRoom,joinRoom,enterRoom,leaveLocal,resume,ensureAuth,roomRef,renderLobby};
}
