(()=>{
const $=id=>document.getElementById(id),boardEl=$('sudokuBoard'),pad=$('numberPad'),timerEl=$('timer'),mistakesEl=$('mistakes'),bestEl=$('bestTime'),difficulty=$('difficulty'),notesBtn=$('notesBtn'),hintBtn=$('hintBtn'),pauseBtn=$('pauseBtn'),pauseOverlay=$('pauseOverlay'),showErrors=$('showErrors'),soundBtn=$('soundBtn'),modal=$('completeModal'),completeText=$('completeText'),confetti=$('confetti');
const audio={tap:new Audio('./assets/sudoku-tap.wav?v=8.1.0'),correct:new Audio('./assets/sudoku-correct.wav?v=8.1.0'),error:new Audio('./assets/sudoku-error.wav?v=8.1.0'),hint:new Audio('./assets/sudoku-hint.wav?v=8.1.0'),complete:new Audio('./assets/sudoku-complete.wav?v=8.1.0')};Object.values(audio).forEach(a=>a.preload='auto');
const state={puzzle:null,solution:null,values:null,notes:Array.from({length:81},()=>new Set()),selected:-1,notesMode:false,mistakes:0,elapsed:0,running:true,lastTick:Date.now(),sound:localStorage.getItem('coffee_sudoku_sound')!=='0',hintCell:-1,difficulty:'easy'};
function play(k){if(!state.sound)return;try{const a=audio[k].cloneNode();a.volume=k==='tap'?.32:.55;a.play().catch(()=>{})}catch{}}
function updateSound(){soundBtn.textContent=state.sound?'🔊':'🔇'}
function shuffled(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function valid(board,idx,n){const r=Math.floor(idx/9),c=idx%9;for(let i=0;i<9;i++){if(board[r*9+i]===n||board[i*9+c]===n)return false}const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)if(board[rr*9+cc]===n)return false;return true}
function fillSolved(board=Array(81).fill(0)){let best=-1,cands=null;for(let i=0;i<81;i++)if(!board[i]){const cs=shuffled([1,2,3,4,5,6,7,8,9].filter(n=>valid(board,i,n)));if(!cs.length)return null;if(!cands||cs.length<cands.length){best=i;cands=cs;if(cs.length===1)break}}if(best<0)return board;for(const n of cands){board[best]=n;const x=fillSolved(board);if(x)return x;board[best]=0}return null}
function countSolutions(board,limit=2){let best=-1,cands=null;for(let i=0;i<81;i++)if(!board[i]){const cs=[1,2,3,4,5,6,7,8,9].filter(n=>valid(board,i,n));if(!cs.length)return 0;if(!cands||cs.length<cands.length){best=i;cands=cs;if(cs.length===1)break}}if(best<0)return 1;let count=0;for(const n of cands){board[best]=n;count+=countSolutions(board,limit-count);board[best]=0;if(count>=limit)return count}return count}
function generate(diff){const givens={easy:40,medium:34,hard:29,expert:26}[diff]||40;const solution=fillSolved(Array(81).fill(0));const puzzle=[...solution],cells=shuffled([...Array(81).keys()]);let left=81;for(const idx of cells){if(left<=givens)break;const old=puzzle[idx];puzzle[idx]=0;if(countSolutions([...puzzle],2)!==1)puzzle[idx]=old;else left--}return{puzzle,solution}}
function format(sec){const m=Math.floor(sec/60),s=sec%60;return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function bestKey(){return`coffee_sudoku_best_${state.difficulty}`}
function updateStats(){timerEl.textContent=format(state.elapsed);mistakesEl.textContent=state.mistakes;const b=Number(localStorage.getItem(bestKey())||0);bestEl.textContent=b?format(b):'--:--'}
function save(){const data={puzzle:state.puzzle,solution:state.solution,values:state.values,notes:state.notes.map(s=>[...s]),selected:state.selected,notesMode:state.notesMode,mistakes:state.mistakes,elapsed:state.elapsed,difficulty:state.difficulty};localStorage.setItem('coffee_sudoku_save',JSON.stringify(data))}
function load(){try{const d=JSON.parse(localStorage.getItem('coffee_sudoku_save')||'null');if(!d?.puzzle?.length||!d?.solution?.length)return false;Object.assign(state,{puzzle:d.puzzle,solution:d.solution,values:d.values,notes:(d.notes||[]).map(a=>new Set(a)),selected:Number(d.selected??-1),notesMode:!!d.notesMode,mistakes:Number(d.mistakes)||0,elapsed:Number(d.elapsed)||0,difficulty:d.difficulty||'easy'});while(state.notes.length<81)state.notes.push(new Set());difficulty.value=state.difficulty;return true}catch{return false}}
function startNew(force=false){if(!force&&state.values&&state.values.some((v,i)=>!state.puzzle[i]&&v)&&!confirm('تبدأ لغز جديد؟'))return;state.difficulty=difficulty.value;const g=generate(state.difficulty);state.puzzle=g.puzzle;state.solution=g.solution;state.values=[...g.puzzle];state.notes=Array.from({length:81},()=>new Set());state.selected=-1;state.notesMode=false;state.mistakes=0;state.elapsed=0;state.running=true;state.lastTick=Date.now();state.hintCell=-1;modal.classList.add('hidden');pauseOverlay.classList.add('hidden');pauseBtn.textContent='⏸ إيقاف مؤقت';notesBtn.textContent='✎ الملاحظات: متوقفة';save();render();updateStats()}
function peers(a,b){if(a<0||b<0)return false;const ar=Math.floor(a/9),ac=a%9,br=Math.floor(b/9),bc=b%9;return ar===br||ac===bc||(Math.floor(ar/3)===Math.floor(br/3)&&Math.floor(ac/3)===Math.floor(bc/3))}
function render(){boardEl.innerHTML='';const selectedVal=state.selected>=0?state.values[state.selected]:0;for(let i=0;i<81;i++){const b=document.createElement('button');b.className='sudoku-cell';if(state.puzzle[i])b.classList.add('given');if(i===state.selected)b.classList.add('selected');else if(state.selected>=0&&peers(i,state.selected))b.classList.add('peer');if(selectedVal&&state.values[i]===selectedVal)b.classList.add('same');if(i===state.hintCell)b.classList.add('hint');const v=state.values[i];if(v){b.textContent=v;if(!state.puzzle[i]&&showErrors.checked&&v!==state.solution[i])b.classList.add('error')}else if(state.notes[i]?.size){const n=document.createElement('div');n.className='notes-grid';for(let x=1;x<=9;x++){const s=document.createElement('span');s.textContent=state.notes[i].has(x)?x:'';n.appendChild(s)}b.appendChild(n)}b.addEventListener('click',()=>select(i));boardEl.appendChild(b)}updateStats()}
function select(i){if(!state.running)return;state.selected=i;state.hintCell=-1;play('tap');render()}
function input(n){const i=state.selected;if(i<0||state.puzzle[i]||!state.running)return;if(state.notesMode){const set=state.notes[i];set.has(n)?set.delete(n):set.add(n);play('tap');save();render();return}state.values[i]=n;state.notes[i].clear();if(n!==state.solution[i]){state.mistakes++;play('error');navigator.vibrate?.(35)}else{play('correct');for(let j=0;j<81;j++)if(peers(i,j))state.notes[j]?.delete(n)}save();render();checkComplete()}
function erase(){const i=state.selected;if(i<0||state.puzzle[i]||!state.running)return;state.values[i]=0;state.notes[i].clear();play('tap');save();render()}
function hint(){if(!state.running)return;let i=state.selected;if(i<0||state.puzzle[i]||state.values[i]===state.solution[i])i=state.values.findIndex((v,j)=>!state.puzzle[j]&&v!==state.solution[j]);if(i<0)return;state.values[i]=state.solution[i];state.notes[i].clear();state.selected=i;state.hintCell=i;play('hint');save();render();setTimeout(()=>{state.hintCell=-1;render()},800);checkComplete()}
function check(){if(!state.running)return;const wrong=state.values.map((v,i)=>v&&v!==state.solution[i]?i:-1).filter(i=>i>=0);if(wrong.length){state.selected=wrong[0];play('error');navigator.vibrate?.([30,30,30]);render()}else if(state.values.every(Boolean))checkComplete();else toast('لحد دلوقتي مفيش أخطاء ظاهرة 👍')}
function checkComplete(){if(!state.values.every((v,i)=>v===state.solution[i]))return;state.running=false;const old=Number(localStorage.getItem(bestKey())||0);if(!old||state.elapsed<old)localStorage.setItem(bestKey(),String(state.elapsed));localStorage.removeItem('coffee_sudoku_save');play('complete');confettiFx();completeText.textContent=`الوقت ${format(state.elapsed)} — الأخطاء ${state.mistakes}`;modal.classList.remove('hidden');updateStats()}
function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.add('hidden'),1800)}
function togglePause(){state.running=!state.running;if(state.running){state.lastTick=Date.now();pauseOverlay.classList.add('hidden');pauseBtn.textContent='⏸ إيقاف مؤقت'}else{pauseOverlay.classList.remove('hidden');pauseBtn.textContent='▶ استئناف';save()}}
function confettiFx(){for(let i=0;i<55;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'%';c.style.background=['#e7bd63','#63cbb0','#e88267','#b692d7'][i%4];c.style.setProperty('--dur',(1.5+Math.random()*1.8)+'s');c.style.setProperty('--drift',((Math.random()-.5)*260)+'px');confetti.appendChild(c);setTimeout(()=>c.remove(),3500)}}
for(let n=1;n<=9;n++){const b=document.createElement('button');b.textContent=n;b.onclick=()=>input(n);pad.appendChild(b)}
$('eraseBtn').onclick=erase;$('checkBtn').onclick=check;hintBtn.onclick=hint;notesBtn.onclick=()=>{state.notesMode=!state.notesMode;notesBtn.textContent=state.notesMode?'✎ الملاحظات: تعمل':'✎ الملاحظات: متوقفة';notesBtn.classList.toggle('primary',state.notesMode);play('tap');save()};pauseBtn.onclick=togglePause;$('newPuzzleBtn').onclick=()=>startNew(false);$('anotherBtn').onclick=()=>startNew(true);$('closeCompleteBtn').onclick=()=>modal.classList.add('hidden');difficulty.onchange=()=>{};showErrors.onchange=render;soundBtn.onclick=()=>{state.sound=!state.sound;localStorage.setItem('coffee_sudoku_sound',state.sound?'1':'0');updateSound()};
window.addEventListener('keydown',e=>{if(e.key>='1'&&e.key<='9')input(Number(e.key));else if(['Backspace','Delete','0'].includes(e.key))erase();else if(e.key==='n'||e.key==='N')notesBtn.click()});
setInterval(()=>{if(state.running){const now=Date.now();if(now-state.lastTick>=1000){const add=Math.floor((now-state.lastTick)/1000);state.elapsed+=add;state.lastTick+=add*1000;updateStats();if(state.elapsed%5===0)save()}}},250);
updateSound();if(!load())startNew(true);else{state.running=true;state.lastTick=Date.now();notesBtn.textContent=state.notesMode?'✎ الملاحظات: تعمل':'✎ الملاحظات: متوقفة';render()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=8.1.0').catch(()=>{});
})();
