import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, onValue, runTransaction } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js?v=8.2.0";
import { makeRoomController } from "./room-helper.js?v=8.2.0";
import { createSocial } from "./social.js?v=8.2.0";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=id=>document.getElementById(id);
const els={homeView:$('homeView'),lobbyView:$('lobbyView'),gameView:$('gameView'),playerName:$('playerName'),avatarPicker:$('avatarPicker'),boardMode:$('boardMode'),create:$('createRoomBtn'),showJoin:$('showJoinBtn'),joinBox:$('joinBox'),roomCodeInput:$('roomCodeInput'),join:$('joinRoomBtn'),copy:$('copyCodeBtn'),share:$('shareRoomBtn'),leaveLobby:$('leaveLobbyBtn'),roomCodeLabel:$('roomCodeLabel'),status:$('statusBanner'),board:$('xoBoard'),myInfo:$('myInfo'),oppInfo:$('opponentInfo'),shareGame:$('shareInGameBtn'),soundBtn:$('soundBtn'),fx:$('xoFxLayer'),rematch:$('rematchBtn'),leaveGame:$('leaveGameBtn'),connection:$('connectionBadge'),reconnect:$('reconnectBanner'),toast:$('toast')};
const state={uid:null,roomCode:null,room:null,roomUnsub:null,avatar:'😎',sound:localStorage.getItem('xo_sound')!=='0',lastMoveNo:null,lastResultKey:null};
const sounds={x:new Audio('./assets/xo-x.wav?v=8.2.0'),o:new Audio('./assets/xo-o.wav?v=8.2.0'),win:new Audio('./assets/xo-win.wav?v=8.2.0'),draw:new Audio('./assets/xo-draw.wav?v=8.2.0')};Object.values(sounds).forEach(a=>a.preload='auto');
function setView(n){['home','lobby','game'].forEach(x=>els[x+'View'].classList.toggle('active',x===n))}
function toast(t){els.toast.textContent=t;els.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add('hidden'),1900)}
function play(k){if(!state.sound)return;try{const a=sounds[k].cloneNode();a.volume=k==='win'?.65:.5;a.play().catch(()=>{})}catch{}}
function soundUi(){if(els.soundBtn)els.soundBtn.textContent=state.sound?'🔊 الصوت':'🔇 الصوت'}
function celebrate(){if(!els.fx)return;for(let i=0;i<42;i++){const c=document.createElement('i');c.className='xo-confetti';c.style.left=(45+Math.random()*10)+'%';c.style.top=(45+Math.random()*8)+'%';c.style.background=['#e6bb64','#63c9b0','#f08b6f','#b18de0'][i%4];c.style.setProperty('--dx',`${(Math.random()-.5)*520}px`);c.style.setProperty('--dy',`${-80-Math.random()*380}px`);c.style.setProperty('--rot',`${Math.random()*720}deg`);els.fx.appendChild(c);setTimeout(()=>c.remove(),1200)}}
function profile(){return{name:(els.playerName.value||'').trim().slice(0,18),avatar:state.avatar}}
function settings(){return{size:Number(els.boardMode.value)||3}}
function otherUid(r=state.room){return r?(r.hostUid===state.uid?r.guestUid:r.hostUid):null}
function symbol(r=state.room,uid=state.uid){return r?.game?.symbols?.x===uid?'x':r?.game?.symbols?.o===uid?'o':null}
function playerCard(p,s,turn){return`<span class="ava">${p?.avatar||'😎'}</span><div><b>${p?.name||'لاعب'}</b><small>${s?.toUpperCase()||''}${turn?' • دوره الآن':''}</small></div>`}
function winner(board,size,win){const dirs=[[1,0],[0,1],[1,1],[1,-1]];for(let r=0;r<size;r++)for(let c=0;c<size;c++){const v=board[r*size+c];if(!v)continue;for(const[dr,dc]of dirs){const line=[];for(let k=0;k<win;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=size||cc<0||cc>=size||board[rr*size+cc]!==v){line.length=0;break}line.push(rr*size+cc)}if(line.length===win)return{symbol:v,line}}}return board.every(Boolean)?{symbol:null,line:[]}:null}
async function startGame(r){if(!r||r.hostUid!==state.uid||!r.guestUid)return;const size=Number(r.settings?.size)||3,now=Date.now(),x=Math.random()<.5?r.hostUid:r.guestUid,o=x===r.hostUid?r.guestUid:r.hostUid;await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='waiting'||room.game)return;room.status='playing';room.game={size,win:size===3?3:4,board:Array(size*size).fill(''),turn:'x',symbols:{x,o},winner:null,winningLine:[],moveNo:0,lastMove:null,startedAt:now,matchNo:1};return room})}
async function move(i){await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='playing'||!room.game)return;const g=room.game,my=symbol(room,state.uid);if(g.turn!==my||g.board[i])return;g.board[i]=my;g.moveNo=(g.moveNo||0)+1;g.lastMove={i,symbol:my,by:state.uid,at:Date.now()};const out=winner(g.board,g.size,g.win);if(out){g.winner=out.symbol;g.winningLine=out.line;room.status='finished'}else g.turn=g.turn==='x'?'o':'x';return room})}
async function rematch(){await runTransaction(ctrl.roomRef(),room=>{if(!room||room.status!=='finished'||!room.game)return;const g=room.game,size=g.size,x=g.symbols.o,o=g.symbols.x;room.status='playing';room.game={size,win:g.win,board:Array(size*size).fill(''),turn:'x',symbols:{x,o},winner:null,winningLine:[],moveNo:0,lastMove:null,startedAt:Date.now(),matchNo:(g.matchNo||1)+1};return room})}
function render(room){state.room=room;const g=room.game;if(!g)return;els.roomCodeLabel.textContent=state.roomCode;const me=symbol(room),opp=me==='x'?'o':'x',ouid=otherUid(room);els.myInfo.innerHTML=playerCard(room.players?.[state.uid],me,room.status==='playing'&&g.turn===me);els.oppInfo.innerHTML=playerCard(room.players?.[ouid],opp,room.status==='playing'&&g.turn===opp);els.myInfo.classList.toggle('turn',room.status==='playing'&&g.turn===me);els.oppInfo.classList.toggle('turn',room.status==='playing'&&g.turn===opp);els.board.style.gridTemplateColumns=`repeat(${g.size},1fr)`;els.board.innerHTML='';g.board.forEach((v,i)=>{const b=document.createElement('button');b.className='xo-cell';if(v)b.innerHTML=`<span class="xo-mark ${v}"></span>`;if(g.lastMove?.i===i)b.classList.add('last-move');if((g.winningLine||[]).includes(i))b.classList.add('win');if(room.status!=='playing'||g.turn!==me||v)b.classList.add('disabled');b.addEventListener('click',()=>move(i));els.board.appendChild(b)});if(room.status==='finished')els.status.textContent=g.winner?(g.winner===me?'🏆 كسبت المباراة!':'صاحبك كسب المباراة'):'🤝 تعادل';else els.status.textContent=g.turn===me?'دورك الآن':'دور صاحبك';els.rematch.disabled=room.status!=='finished';social.render(room);
 const mv=Number(g.moveNo||0);if(state.lastMoveNo===null||mv<state.lastMoveNo){state.lastMoveNo=mv}else if(mv>state.lastMoveNo){state.lastMoveNo=mv;if(g.lastMove?.symbol)play(g.lastMove.symbol);navigator.vibrate?.(18)}
 const resultKey=room.status==='finished'?`${g.matchNo||1}:${g.winner||'draw'}`:null;if(resultKey&&resultKey!==state.lastResultKey){state.lastResultKey=resultKey;setTimeout(()=>{if(g.winner){play('win');if(g.winner===me){celebrate();navigator.vibrate?.([45,35,70])}}else play('draw')},160)}if(!resultKey)state.lastResultKey=null}
const ctrl=makeRoomController({db,auth,state,gameType:'xo',getProfile:profile,getSettings:settings,setView,onRoom:render,onHostReady:startGame,toast});
const social=createSocial({db,state,getProfile:profile,toast});
onValue(ref(db,'.info/connected'),s=>{const ok=s.val()===true;els.connection.textContent=ok?'متصل':'غير متصل';els.connection.classList.toggle('offline',!ok);els.reconnect.classList.toggle('hidden',ok)});
els.avatarPicker.addEventListener('click',e=>{const b=e.target.closest('button[data-avatar]');if(!b)return;state.avatar=b.dataset.avatar;els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));localStorage.setItem('coffee_avatar',state.avatar)});
els.create.addEventListener('click',()=>{localStorage.setItem('coffee_name',profile().name);localStorage.setItem('xo_size',els.boardMode.value);ctrl.createRoom()});els.showJoin.addEventListener('click',()=>els.joinBox.classList.toggle('hidden'));els.join.addEventListener('click',()=>ctrl.joinRoom(els.roomCodeInput.value));els.roomCodeInput.addEventListener('keydown',e=>e.key==='Enter'&&ctrl.joinRoom(els.roomCodeInput.value));els.leaveLobby.addEventListener('click',()=>{social.cleanup();ctrl.leaveLocal()});els.leaveGame.addEventListener('click',()=>{social.cleanup();ctrl.leaveLocal()});els.rematch.addEventListener('click',rematch);
async function share(){const u=new URL('./xo.html',location.href);u.searchParams.set('room',state.roomCode);if(navigator.share){try{return await navigator.share({title:'القهوة — XO',text:`تعالى نلعب XO — كود ${state.roomCode}`,url:u.href})}catch{}}await navigator.clipboard.writeText(u.href);toast('تم نسخ الرابط')}
els.copy.addEventListener('click',()=>navigator.clipboard.writeText(state.roomCode).then(()=>toast('تم نسخ الكود')));els.share.addEventListener('click',share);els.shareGame.addEventListener('click',share);els.soundBtn?.addEventListener('click',()=>{state.sound=!state.sound;localStorage.setItem('xo_sound',state.sound?'1':'0');soundUi()});
(async()=>{soundUi();els.playerName.value=localStorage.getItem('coffee_name')||'';state.avatar=localStorage.getItem('coffee_avatar')||'😎';els.avatarPicker.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===state.avatar));els.boardMode.value=localStorage.getItem('xo_size')||'3';if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=8.2.0').catch(()=>{});await ctrl.resume()})().catch(console.error);
